#!/usr/bin/env python3
"""Compress the local pet dashboard into a deterministic PROGMEM header."""

from __future__ import annotations

import argparse
import gzip
from pathlib import Path


def compress(source: bytes) -> bytes:
    # Gzip's timestamp is explicitly fixed so a rebuild changes the header only
    # when the source changes.  This is served with Content-Encoding: gzip.
    payload = bytearray(gzip.compress(source, compresslevel=9, mtime=0))
    # Python 3.11 and 3.12 use OS=3 for mtime=0 while newer versions use
    # OS=255. Normalize it so generated headers are portable across builders.
    payload[9] = 255
    return bytes(payload)


def render_header(payload: bytes) -> str:
    values = ",".join(f"0x{byte:02x}" for byte in payload)
    return (
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "#include <stddef.h>\n\n"
        "// Generated by tools/build_pet_page.py; do not edit this file directly.\n"
        "// The server must send Content-Encoding: gzip and the exact byte length.\n"
        "const uint8_t PET_PAGE_GZIP[] PROGMEM = {"
        + values
        + "};\n"
        "const size_t PET_PAGE_GZIP_SIZE = sizeof(PET_PAGE_GZIP);\n"
    )


def build(source: Path, destination: Path) -> bytes:
    compressed = compress(source.read_bytes())
    destination.parent.mkdir(parents=True, exist_ok=True)
    header = render_header(compressed)
    if not destination.exists() or destination.read_text(encoding="utf-8") != header:
        destination.write_text(header, encoding="utf-8")
    return compressed


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=root / "web/pet.html")
    parser.add_argument("--output", type=Path, default=root / "src/pet_page.h")
    args = parser.parse_args()
    build(args.source, args.output)


if __name__ == "__main__":
    main()
