#!/usr/bin/env python3
"""Compress the dashboard deterministically without changing its readable source."""
import argparse
import gzip
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate():
    source = (ROOT / "src/page.h").read_text(encoding="utf-8")
    html = source.split('R"HTML(', 1)[1].rsplit(')HTML"', 1)[0].encode("utf-8")
    data = bytearray(gzip.compress(html, compresslevel=9, mtime=0))
    data[9] = 255  # Normalize the OS field across Python gzip implementations.
    rows = [", ".join(f"0x{byte:02x}" for byte in data[i:i + 16]) for i in range(0, len(data), 16)]
    return ("// Generated by tools/build_dashboard_page.py; edit src/page.h.\n"
            "#pragma once\n#include <Arduino.h>\n"
            "static const uint8_t DASHBOARD_GZIP[] PROGMEM = {\n  " + ",\n  ".join(rows) +
            "\n};\nstatic constexpr size_t DASHBOARD_GZIP_SIZE = sizeof(DASHBOARD_GZIP);\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "src/page_gzip.h"
    generated = generate()
    if args.check:
        if not path.exists() or path.read_text() != generated:
            raise SystemExit("dashboard header is stale; run tools/build_dashboard_page.py")
    elif not path.exists() or path.read_text() != generated:
        path.write_text(generated)
