#pragma once

#include <stddef.h>
#include <stdio.h>

namespace round_ui {

// Only an IPv4 address generated by the network stack is encoded. Never put
// credentials or arbitrary host/path input into the display link.
inline bool validDashboardIp(const char* ip) {
  if (!ip) return false;
  const char* cursor = ip;
  for (unsigned part = 0; part < 4; ++part) {
    unsigned value = 0, digits = 0;
    while (*cursor >= '0' && *cursor <= '9') {
      value = value * 10 + (*cursor++ - '0');
      if (++digits > 3 || value > 255) return false;
    }
    if (!digits || (part == 0 && (value == 0 || value >= 224))) return false;
    if (part < 3) {
      if (*cursor++ != '.') return false;
    } else if (*cursor != '\0') {
      return false;
    }
  }
  return true;
}

inline bool dashboardUrl(bool connected, bool portal, const char* ip,
                         char* output, size_t capacity) {
  if (!output || !capacity) return false;
  output[0] = '\0';
  if ((!connected && !portal) || !validDashboardIp(ip)) return false;
  const int length = snprintf(output, capacity, "http://%s/", ip);
  if (length < 0 || static_cast<size_t>(length) >= capacity) {
    output[0] = '\0';
    return false;
  }
  return true;
}

}  // namespace round_ui
