#pragma once
// Dashboard HTML for the C3 AdBlocker web UI, kept in its own header so the
// Arduino IDE preprocessor doesn't choke on the inlined markup (issue #6).

const char PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f8f7">
<title>AdBlock · Consola</title><style>
:root{--ink:#102b34;--muted:#64777c;--line:#d8e2e1;--paper:#f6f8f7;--panel:#fff;--teal:#087f78;--teal-dark:#05645f;--teal-soft:#dff3ef;--amber:#b56a13;--red:#b5443b;--shadow:0 12px 30px rgba(16,43,52,.07);--radius:14px}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.01em}button,input,select{font:inherit}button{border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--ink);padding:8px 12px;cursor:pointer;transition:background .15s,border-color .15s,transform .15s}button:hover{border-color:#9db5b2;background:#f1f7f5}button:active{transform:translateY(1px)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid rgba(8,127,120,.25);outline-offset:2px}.primary{background:var(--teal);border-color:var(--teal);color:#fff;font-weight:650}.primary:hover{background:var(--teal-dark);border-color:var(--teal-dark)}.quiet{padding:6px 9px;color:var(--muted);background:transparent}.danger{color:var(--red)}.wrap{width:min(1160px,calc(100% - 32px));margin:0 auto;padding:24px 0 56px}
.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:26px}.eyebrow{color:var(--teal);font-size:11px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.brand{margin:4px 0 3px;font-size:clamp(24px,4vw,35px);letter-spacing:-.04em;line-height:1.1}.sub{margin:0;color:var(--muted)}.topbar-actions{display:flex;align-items:center;gap:10px}.language-control{display:grid;gap:4px}.language-feedback:empty{display:none}.language-control select{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);font-size:12px;padding:9px 11px}.language-control select:disabled{opacity:.55;cursor:not-allowed}.host{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;padding:9px 11px;border:1px solid var(--line);background:#fff;border-radius:999px;white-space:nowrap}.dot{width:8px;height:8px;border-radius:99px;background:var(--teal);box-shadow:0 0 0 4px var(--teal-soft)}.dot.off{background:var(--red);box-shadow:0 0 0 4px #fae6e3}
.status{display:flex;align-items:center;gap:14px;padding:16px 18px;margin-bottom:18px;background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--teal);border-radius:var(--radius);box-shadow:var(--shadow)}.status.paused{border-left-color:var(--amber)}.shield{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:var(--teal-soft);font-size:19px}.paused .shield{background:#fff1da}.status-copy{flex:1;min-width:0}.status-title{display:block;font-size:15px;font-weight:750}.status-note{display:block;color:var(--muted);font-size:12px;margin-top:2px}.status-actions{display:flex;align-items:center;gap:8px}.status select{border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);padding:8px}.status select[hidden]{display:none}
.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:22px}.metric{padding:15px 16px;background:var(--panel);border:1px solid var(--line);border-radius:12px}.metric-value{font-size:24px;font-weight:760;letter-spacing:-.04em;line-height:1.1}.metric-label{color:var(--muted);font-size:12px;margin-top:6px}.metric-value.good{color:var(--teal)}.metric-value.warn{color:var(--amber)}
.section-label{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin:24px 0 9px}.section-label h2{margin:0;font-size:14px;letter-spacing:.04em}.section-label p{margin:0;color:var(--muted);font-size:12px}.layout{display:grid;grid-template-columns:minmax(0,1fr);gap:18px;align-items:start}.panel{min-width:0;background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:18px 18px 14px;border-bottom:1px solid var(--line)}.panel-title{margin:0;font-size:17px;letter-spacing:-.02em}.panel-kicker{margin:4px 0 0;color:var(--muted);font-size:12px}.log-tools{display:flex;align-items:center;gap:8px}.search{width:min(220px,42vw);border:1px solid var(--line);border-radius:9px;padding:8px 10px;color:var(--ink);background:#fbfcfc}.table-scroll{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:11px 18px;text-align:left;border-bottom:1px solid #e8eeed;font-size:13px;white-space:nowrap}th{color:var(--muted);font-size:11px;font-weight:750;letter-spacing:.08em;text-transform:uppercase;background:#fbfcfc}tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:#f7fbfa}.domain{font-weight:680;color:var(--ink);white-space:normal;overflow-wrap:anywhere;max-width:360px}.client{color:var(--muted);font-variant-numeric:tabular-nums}.reason{display:inline-flex;padding:3px 7px;border-radius:999px;background:var(--teal-soft);color:var(--teal-dark);font-size:11px;font-weight:700}.reason.custom{background:#fff1da;color:#89500d}.reason.client{background:#fae6e3;color:#993c35}.age{color:var(--muted);font-variant-numeric:tabular-nums}.empty{padding:30px 18px;color:var(--muted);text-align:center}.log-foot{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 18px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.pager{display:flex;gap:6px}.pager button{padding:5px 9px}.pager button:disabled{opacity:.45;cursor:not-allowed}.log-error{display:none;margin:0 18px 14px;padding:9px 11px;border-radius:8px;color:var(--red);background:#fff2f0;font-size:12px}.log-error.show{display:block}
.side{min-width:0;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px}.side .panel-head{padding-bottom:13px}.client-table th,.client-table td{padding-left:16px;padding-right:16px}.client-table td:nth-child(3),.client-table td:nth-child(4){text-align:right}.num{font-variant-numeric:tabular-nums}.block-num{color:var(--red)}.allow-num{color:var(--teal)}.badge{display:inline-flex;padding:2px 6px;border-radius:999px;background:#fae6e3;color:var(--red);font-size:10px;font-weight:800;margin-left:5px}.custom-list{padding:0 16px}.custom-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 2px;border-bottom:1px solid #e8eeed}.custom-row:last-child{border-bottom:0}.domain-form,.settings-form,.upload-form{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.panel-body{padding:15px 16px}.field{min-width:0;flex:1;border:1px solid var(--line);border-radius:8px;background:#fbfcfc;color:var(--ink);padding:8px 10px}.field.short{flex:0 1 70px;min-width:58px}.hint{margin:8px 0 0;color:var(--muted);font-size:11px}.form-status{color:var(--muted);font-size:12px}.settings-grid{display:grid;gap:13px}.settings-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.settings-row label{width:100%;font-size:12px;font-weight:700;color:var(--muted)}.file{max-width:100%;font-size:12px}.stack{display:grid;gap:8px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.offline{color:var(--red)!important}.sr-only{position:absolute;left:0;top:0;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.list-status{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.list-status strong{font-size:13px}.list-status .form-status{margin-left:auto}.profile-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.4fr);gap:14px;align-items:start}.profile-picker{display:grid;gap:8px}.profile-picker label{font-size:12px;font-weight:700;color:var(--muted)}.profile-picker select{width:100%;border:1px solid var(--line);border-radius:8px;background:#fbfcfc;color:var(--ink);padding:9px 10px}.profile-meta{display:grid;gap:5px}.profile-meta p{margin:0;color:var(--muted);font-size:12px}.profile-meta strong{color:var(--ink)}.profile-progress{width:100%;height:8px;accent-color:var(--teal)}.allow-note{margin:0 0 12px;color:var(--muted);font-size:12px}.allow-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 2px;border-bottom:1px solid #e8eeed}.allow-row:last-child{border-bottom:0}.allow-list{padding:0 16px;max-height:280px;overflow:auto}.allow-list .empty{padding:18px 2px}.log-action{padding:5px 8px;font-size:11px}.profile-error{display:none;width:100%;margin:4px 0 0;padding:8px 10px;border-radius:8px;color:var(--red);background:#fff2f0;font-size:12px}.profile-error.show{display:block}
@media(max-width:860px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.layout{grid-template-columns:minmax(0,1fr)}.side{display:flex;flex-direction:column}.side .panel:last-child{grid-column:1/-1}}@media(max-width:560px){.wrap{width:min(100% - 22px,1160px);padding-top:18px}.topbar{display:block}.host{display:inline-flex;margin-top:14px}.status{align-items:flex-start;flex-wrap:wrap}.status-actions{width:100%;justify-content:flex-end}.status-actions select{flex:1}.panel-head{display:block}.log-tools{margin-top:12px}.search{width:100%}.metrics{gap:8px}.metric{padding:13px}.metric-value{font-size:20px}.side{display:flex}th,td{padding-left:12px;padding-right:12px}.log-foot{align-items:flex-start;flex-direction:column}.pager{align-self:flex-end}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
 </style></head><body><main class="wrap"><header class="topbar"><div><div class="eyebrow">Protección de tu red</div><h1 class="brand">AdBlock</h1><p class="sub">Consulta qué se bloquea y controla la protección de tu red.</p></div><div class="topbar-actions"><div id="languageControl" class="language-control"><label for="languageSelect" class="sr-only" id="languageLabel">Idioma</label><select id="languageSelect" aria-labelledby="languageLabel"><option value="es">Español</option><option value="en">English</option></select><span id="languageStatus" class="form-status language-feedback" role="status"></span></div><div id="connection" class="host"><span class="dot" aria-hidden="true"></span><span id="host">Conectando…</span></div></div></header>
<section id="blockbar" class="status" aria-live="polite"><div id="blockdot" class="shield" aria-hidden="true">✓</div><div class="status-copy"><span id="blockstate" class="status-title">Comprobando bloqueo…</span><span id="blocknote" class="status-note">Sincronizando con el dispositivo</span></div><div class="status-actions"><label class="sr-only" for="pausedur">Duración de la pausa</label><select id="pausedur"><option value="30">30 segundos</option><option value="300" selected>5 minutos</option><option value="1800">30 minutos</option><option value="0">Hasta reactivar</option></select><button id="pausebtn" class="primary" type="button" disabled>Pausar</button></div></section>
<section id="sys" class="metrics" aria-label="Estado del sistema"></section>
<div class="section-label"><h2>ACTIVIDAD</h2><p id="lastRefresh">Actualizando…</p></div><div class="layout"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Consultas bloqueadas</h2><p class="panel-kicker">Las últimas solicitudes rechazadas por el dispositivo</p></div><div class="log-tools"><label class="sr-only" for="logSearch">Filtrar por dominio o cliente</label><input id="logSearch" class="search" maxlength="63" type="search" placeholder="Buscar dominio o IP…" autocomplete="off"></div></div><p id="logError" class="log-error" role="alert"></p><div class="table-scroll"><table aria-live="polite"><thead><tr><th>Dominio</th><th>Cliente</th><th>Tipo</th><th>Motivo</th><th>Hace</th><th><span class="sr-only">Acción</span></th></tr></thead><tbody id="logBody"></tbody></table></div><div class="log-foot"><span id="logMeta">Cargando historial…</span><div class="pager"><button id="prevPage" type="button" disabled>Anterior</button><button id="nextPage" type="button" disabled>Siguiente</button></div></div></section>
<aside class="side"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Clientes</h2><p class="panel-kicker">Actividad observada desde el último arranque</p></div></div><div class="table-scroll"><table class="client-table"><thead><tr><th>IP</th><th>MAC</th><th>Bloq.</th><th>Permit.</th><th><span class="sr-only">Acción</span></th></tr></thead><tbody id="clientBody"></tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Dominios propios</h2><p class="panel-kicker">Reglas añadidas manualmente</p></div></div><div class="panel-body"><form id="domainForm" class="domain-form"><label class="sr-only" for="dom">Dominio que bloquear</label><input id="dom" class="field" maxlength="253" placeholder="ads.example.com" autocomplete="off"><button class="primary" type="submit">Bloquear</button></form></div><div id="customBody" class="custom-list"></div></section></aside></div>
<div class="section-label"><h2>LISTAS DE BLOQUEO</h2><p>El perfil activo se mantiene hasta que la nueva lista termine de aplicarse.</p></div><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Perfil de protección</h2><p class="panel-kicker">Elige el nivel de cobertura de HaGeZi y revisa el cambio antes de aplicarlo.</p></div><div class="list-status"><strong id="listsCount">— dominios</strong><span id="listsStatus" class="form-status" role="status">Cargando…</span></div></div><div class="panel-body profile-grid"><div class="profile-picker"><label for="profileSelect">Perfil seleccionado</label><select id="profileSelect" disabled><option value="custom">Personalizada · lista actual</option><option value="light">Ligero · HaGeZi Light</option><option value="balanced">Equilibrado · HaGeZi PRO (recomendado)</option><option value="strict">Estricto · HaGeZi PRO++ (puede romper sitios)</option></select><button id="profileApply" class="primary" type="button" disabled>Aplicar perfil</button><button id="listsCheck" type="button" disabled>Actualizar lista ahora</button><p id="listsError" class="profile-error" role="alert"></p></div><div class="profile-meta"><p id="listsActive">Activa: —</p><p id="listsSelected">Seleccionada: —</p><progress id="listsProgress" class="profile-progress" max="100" value="0" hidden></progress><p id="listsProgressText">La lista personalizada conserva la configuración existente.</p><p class="hint">Personalizada usa la carga binaria y la URL configuradas más abajo; elegir un perfil no cambia la lista hasta que termine la comprobación y aplicación.</p></div></div></section><section class="panel" style="margin-top:12px"><div class="panel-head"><div><h2 class="panel-title">Dominios permitidos</h2><p class="panel-kicker">Excepciones persistentes para esta red</p></div><span id="allowCount" class="form-status">0 / 200</span></div><div class="panel-body"><p class="allow-note">Permite este dominio y sus subdominios aunque aparezca en una blocklist o regla propia. Las prohibiciones de clientes siguen teniendo prioridad.</p><form id="allowlistForm" class="domain-form"><label class="sr-only" for="allowDomain">Dominio que permitir</label><input id="allowDomain" class="field" maxlength="253" placeholder="example.com" autocomplete="off"><button id="allowAdd" class="primary" type="submit" disabled>Permitir dominio</button><span id="allowStatus" class="form-status" role="status"></span></form></div><div id="allowBody" class="allow-list"></div></section>
<div class="section-label"><h2>CONFIGURACIÓN</h2><p>Los cambios se aplican al dispositivo al guardarlos.</p></div><section class="panel" style="margin-bottom:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Wi-Fi y acceso</h2><p class="panel-kicker">Cambia de red conservando las listas, las excepciones y los ajustes.</p></div><div class="settings-row"><strong id="wifiNetwork">Consultando red…</strong><button id="wifiChange" type="button" disabled>Cambiar Wi-Fi</button></div><p id="wifiStatus" class="form-status" role="status"></p><div id="wifiInstructions" hidden><p>Conecta a la red <strong id="wifiAp">C3-AdBlock-XXXX</strong> y abre <a href="http://192.168.4.1/" target="_blank" rel="noopener">192.168.4.1</a> para elegir la nueva Wi-Fi.</p><p class="hint">La red anterior se conserva hasta comprobar la nueva conexión. Puedes cancelar desde la página de configuración para volver a ella.</p></div><p class="hint">Usa una red de 2,4 GHz. Si cambia la IP del dispositivo, actualiza la dirección DNS en tu router o equipos.</p></div></section><section class="panel"><div class="panel-body settings-grid"><div><h2 class="panel-title">Personalizada · Blocklist local</h2><p class="panel-kicker">Carga una lista binaria ya compilada, sin USB.</p></div><form id="uploadForm" class="upload-form"><label class="sr-only" for="blf">Archivo blocklist.bin</label><input id="blf" class="file" type="file" accept=".bin"><button type="submit">Subir blocklist</button><span id="upmsg" class="form-status" role="status"></span></form><p class="hint">Genera <span class="mono">blocklist.bin</span> con <span class="mono">tools/build_blocklist.py</span>.</p></div></section>
<section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Personalizada · Actualización remota</h2><p class="panel-kicker">Descarga una blocklist precompilada según un horario.</p></div><form id="updateForm" class="settings-form"><label class="sr-only" for="uurl">URL de blocklist</label><input id="uurl" class="field" type="url" placeholder="https://host/blocklist.bin" autocomplete="off"><label class="sr-only" for="uiv">Intervalo en horas</label><input id="uiv" class="field short" type="number" min="1" max="720" value="24"><span aria-hidden="true">h</span><button type="submit">Guardar</button><button id="fetchNow" type="button">Descargar ahora</button><span id="ustat" class="form-status" role="status">—</span></form><p class="hint">El dispositivo mantiene la última respuesta aquí; una URL vacía desactiva la descarga personalizada. El intervalo también se usa para los perfiles HaGeZi.</p></div></section>
<section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Firmware · OTA</h2><p class="panel-kicker">El dispositivo valida el binario y reinicia en la nueva versión.</p></div><form id="firmwareForm" class="upload-form"><label class="sr-only" for="fwb">Archivo de firmware</label><input id="fwb" class="file" type="file" accept=".bin"><button type="submit">Flashear firmware</button><span id="fwmsg" class="form-status" role="status"></span></form><p class="hint">Selecciona <span class="mono">firmware.bin</span> o el binario de tu perfil.</p></div></section><section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Actualización desde GitHub</h2><p class="panel-kicker">Busca una release pública para este perfil y verifica tamaño y SHA-256.</p></div><div class="upload-form"><button id="githubCheck" type="button" disabled>Comprobar actualizaciones</button><button id="githubInstall" class="primary" type="button" disabled>Instalar actualización</button><span id="githubStatus" class="form-status" role="status">Nunca comprobado</span></div><p id="fwIdentity" class="hint">Leyendo versión instalada…</p><p class="hint">Releases de felipedelpozo/adblock. La instalación conserva WiFi, listas y ajustes.</p></div></section><p class="hint" style="margin-top:18px"><strong>Últimas 64 consultas:</strong> historial reciente; se vacía al reiniciar la placa. Los contadores de esta sesión siguen la misma regla.</p></main>
<script>
const $=id=>document.getElementById(id);
const state={logPage:0,logQuery:'',logBusy:false,logPending:false,statsBusy:false,searchTimer:0,offline:false,updateDirty:false,githubNonce:'',githubVersion:'',githubPending:false,githubCanInstall:false,listsReady:false,listsBusy:false,listsFetchBusy:false,listsAction:false,listsProfileDirty:false,listsProfileDraft:'',listsAppliedProfile:'custom',listsNonce:'',listsPollTimer:0,allowed:[],allowlistBusy:false,wifiAp:'',wifiFirmwareBusy:false,wifiPending:false,wifiReconfiguring:false};
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node}
function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}
async function request(path,options){const response=await fetch(path,options);if(!response.ok){const error=new Error('HTTP '+(response.status||0));error.status=response.status||0;throw error}return response}
function actionStatus(node,message,error){node.textContent=message;node.classList.toggle('offline',!!error)}
function metric(label,value,tone){const card=el('div','metric');card.append(el('div','metric-value '+(tone||''),value),el('div','metric-label',label));return card}
function showListsError(message){const node=$('listsError');node.textContent=message||'';node.classList.toggle('show',!!message)}
function listsHeaders(){return {'X-CSRF-Token':state.listsNonce}}
async function listsRequest(path,options){const opts=options||{};const headers=Object.assign({},opts.headers||{},listsHeaders());return request(path,Object.assign({},opts,{headers}))}
function updateListsControls(){const disabled=!state.listsReady||state.listsBusy||state.listsAction||state.wifiReconfiguring;$('profileSelect').disabled=disabled;$('profileApply').disabled=disabled||state.listsProfileDraft===state.listsAppliedProfile||state.listsProfileDraft==='custom';$('listsCheck').disabled=disabled||state.listsProfileDraft==='custom';$('allowAdd').disabled=!state.listsReady||state.listsBusy||state.allowlistBusy||state.wifiReconfiguring;updateWifiControls()}
async function loadLists(){if(state.wifiReconfiguring)return;if(state.listsFetchBusy||state.listsAction)return;state.listsFetchBusy=true;try{const data=await(await request('/lists.json')).json();if(state.wifiReconfiguring)return;if(!data||typeof data!=='object')throw new Error('Invalid lists response');state.listsNonce=typeof data.nonce==='string'?data.nonce:state.listsNonce;state.listsReady=true;renderLists(data);showListsError('')}catch(error){showListsError(listsErrorMessage(error,t('listLoad')))}finally{state.listsFetchBusy=false}}
function scheduleListsPoll(){clearTimeout(state.listsPollTimer);state.listsPollTimer=setTimeout(()=>{loadLists()},450)}
async function listsAction(path,successMessage){if(!state.listsReady||state.listsAction||state.listsBusy)return;state.listsAction=true;showListsError('');updateListsControls();let accepted=false;try{const response=await listsRequest(path,{method:'POST'});if(response.status!==202)throw Object.assign(new Error('Unexpected response'),{status:response.status});accepted=true;state.listsBusy=true;$('listsStatus').textContent=successMessage;$('listsProgress').value=0;$('listsProgress').hidden=false;$('listsProgressText').textContent=t('requestAccepted');updateListsControls();scheduleListsPoll()}catch(error){showListsError(listsErrorMessage(error,t('listStart')));}finally{state.listsAction=false;if(!accepted)state.listsBusy=false;updateListsControls()}}
async function changeAllowlist(domain,remove){if(!state.listsReady||state.allowlistBusy||state.listsBusy||state.listsAction)return;const value=String(domain||'').trim().toLowerCase().replace(/^\.+|\.+$/g,'');if(!value||value.length>253){$('allowStatus').textContent=t('invalidDomain');$('allowStatus').classList.add('offline');return}state.allowlistBusy=true;$('allowStatus').classList.remove('offline');$('allowStatus').textContent=remove?t('removing'):t('allowing');try{const response=await listsRequest((remove?'/allowlist/remove?d=':'/allowlist/add?d=')+encodeURIComponent(value),{method:'POST'});if(response.status!==200)throw Object.assign(new Error('Unexpected response'),{status:response.status});$('allowStatus').textContent=remove?t('allowRemoved'):t('allowed');if(!remove)$('allowDomain').value='';await loadLists()}catch(error){$('allowStatus').textContent=allowlistErrorMessage(error,remove);$('allowStatus').classList.add('offline')}finally{state.allowlistBusy=false;renderAllowed(state.allowed);updateListsControls()}}
function requestLog(){if(state.wifiReconfiguring)return;if(state.logBusy){state.logPending=true;return}loadLog()}
async function loadLog(){if(state.logBusy){state.logPending=true;return}state.logBusy=true;state.logPending=false;const page=state.logPage;const query=state.logQuery;const error=$('logError');error.classList.remove('show');const path='/blocked.json?offset='+(page*16)+'&limit=16&q='+encodeURIComponent(query.slice(0,63));try{const data=await(await request(path)).json();if(state.wifiReconfiguring)return;if(page!==state.logPage||query!==state.logQuery){state.logPending=true;return}const maxPage=Math.max(0,Math.ceil((Number(data.count)||0)/16)-1);if(state.logPage>maxPage){state.logPage=maxPage;state.logPending=true;return}renderLog(data);$('lastRefresh').textContent=t('updatedAt',{time:new Date().toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit'})});setOffline(false)}catch(_){error.textContent=t('offlineHistory');error.classList.add('show');$('prevPage').disabled=true;$('nextPage').disabled=true;setOffline(true)}finally{state.logBusy=false;if(state.logPending){state.logPending=false;requestLog()}}}
async function loadStats(){if(state.statsBusy||state.wifiReconfiguring)return;state.statsBusy=true;const languageEpoch=state.languageEpoch;try{const s=await(await request('/stats.json')).json();if(state.wifiReconfiguring)return;const connection=$('connection');connection.dataset.ip=s.ip;renderStatus(s);renderMetrics(s,languageEpoch!==state.languageEpoch);renderClients(s.clients);renderCustom(s.custom);if(!state.updateDirty){$('uurl').value=s.upurl||'';$('uiv').value=s.upiv||24}$('ustat').textContent=s.upstat||'—';renderFirmware(s);renderWifi(s);setOffline(false)}catch(_){if(state.wifiReconfiguring)return;setOffline(true);$('blockstate').textContent=t('offlineDevice');$('blocknote').textContent=t('offlineRetry')}finally{state.statsBusy=false}}
function updateWifiControls(){$('wifiChange').disabled=!state.githubNonce||!state.wifiAp||state.offline||state.wifiFirmwareBusy||state.githubPending||state.listsBusy||state.listsAction||state.wifiPending||state.wifiReconfiguring;if(typeof updateLanguageControl==='function')updateLanguageControl()}
const I18N={
  es:{
    title:'AdBlock · Consola',languageLabel:'Idioma',eyebrow:'Protección de tu red',sub:'Consulta qué se bloquea y controla la protección de tu red.',
    connecting:'Conectando…',device:'dispositivo',checkingBlocking:'Comprobando bloqueo…',syncingDevice:'Sincronizando con el dispositivo',loading:'Cargando…',pauseDuration:'Duración de la pausa',pause30:'30 segundos',pause5:'5 minutos',pause30m:'30 minutos',pauseUntil:'Hasta reactivar',pause:'Pausar',resume:'Reanudar',
    system:'Estado del sistema',activity:'ACTIVIDAD',updating:'Actualizando…',blockedQueries:'Consultas bloqueadas',blockedQueriesKicker:'Las últimas solicitudes rechazadas por el dispositivo',
    filterLog:'Filtrar por dominio o cliente',searchPlaceholder:'Buscar dominio o IP…',domain:'Dominio',client:'Cliente',type:'Tipo',reason:'Motivo',age:'Hace',action:'Acción',
    loadingHistory:'Cargando historial…',previous:'Anterior',next:'Siguiente',clients:'Clientes',clientsKicker:'Actividad observada desde el último arranque',clientIp:'IP',clientMac:'MAC',blockedShort:'Bloq.',allowedShort:'Permit.',
    customDomains:'Dominios propios',customDomainsKicker:'Reglas añadidas manualmente',domainToBlock:'Dominio que bloquear',block:'Bloquear',domainPlaceholder:'ads.example.com',
    noClients:'Sin clientes todavía',blockedBadge:'BLOQUEADO',unblockClient:'Desbloquear',blockClient:'Bloquear',remove:'Quitar',noCustom:'Todavía no hay dominios propios.',
    lists:'LISTAS DE BLOQUEO',listsIntro:'El perfil activo se mantiene hasta que la nueva lista termine de aplicarse.',protectionProfile:'Perfil de protección',
    profileKicker:'Elige el nivel de cobertura de HaGeZi y revisa el cambio antes de aplicarlo.',selectedProfile:'Perfil seleccionado',
    customProfile:'Personalizada · lista actual',lightProfile:'Ligero · HaGeZi Light',balancedProfile:'Equilibrado · HaGeZi PRO (recomendado)',strictProfile:'Estricto · HaGeZi PRO++ (puede romper sitios)',
    applyProfile:'Aplicar perfil',refreshList:'Actualizar lista ahora',listActive:'Activa: {value}',listSelected:'Seleccionada: {value}',profileProgress:'Progreso: {value}% · el perfil activo sigue siendo {profile}',
    applied:'Lista aplicada: {profile}',customListPreserved:'La lista personalizada conserva la configuración existente.',customListHint:'Personalizada usa la carga binaria y la URL configuradas más abajo; elegir un perfil no cambia la lista hasta que termine la comprobación y aplicación.',
    preparing:'Lista preparada',noAllow:'Todavía no hay excepciones guardadas.',allowDomains:'Dominios permitidos',allowDomainsKicker:'Excepciones persistentes para esta red',allowNote:'Permite este dominio y sus subdominios aunque aparezca en una blocklist o regla propia. Las prohibiciones de clientes siguen teniendo prioridad.',
    domainToAllow:'Dominio que permitir',allow:'Permitir dominio',allowPlaceholder:'example.com',allowCount:'{count} / 200',allowing:'Guardando…',removing:'Quitando…',allowed:'Dominio permitido',allowRemoved:'Excepción quitada',
    settings:'CONFIGURACIÓN',settingsIntro:'Los cambios se aplican al dispositivo al guardarlos.',wifiAccess:'Wi-Fi y acceso',wifiKicker:'Cambia de red conservando las listas, las excepciones y los ajustes.',
    currentNetwork:'Red actual: {ssid}',queryingNetwork:'Consultando red…',changeWifi:'Cambiar Wi-Fi',wifiSetupInstructions:'Conecta a la red {ap} y abre 192.168.4.1 para elegir la nueva Wi-Fi.',
    wifiOldHint:'La red anterior se conserva hasta comprobar la nueva conexión. Puedes cancelar desde la página de configuración para volver a ella.',wifi24Hint:'Usa una red de 2,4 GHz. Si cambia la IP del dispositivo, actualiza la dirección DNS en tu router o equipos.',
    localBlocklist:'Personalizada · Blocklist local',localBlocklistKicker:'Carga una lista binaria ya compilada, sin USB.',blocklistFile:'Archivo blocklist.bin',uploadBlocklist:'Subir blocklist',
    buildHint:'Genera blocklist.bin con tools/build_blocklist.py.',remoteUpdate:'Personalizada · Actualización remota',remoteKicker:'Descarga una blocklist precompilada según un horario.',
    blocklistUrl:'URL de blocklist',interval:'Intervalo en horas',save:'Guardar',downloadNow:'Descargar ahora',remoteHint:'El dispositivo mantiene la última respuesta aquí; una URL vacía desactiva la descarga personalizada. El intervalo también se usa para los perfiles HaGeZi.',
    firmware:'Firmware · OTA',firmwareKicker:'El dispositivo valida el binario y reinicia en la nueva versión.',firmwareFile:'Archivo de firmware',flashFirmware:'Flashear firmware',firmwareHint:'Selecciona firmware.bin o el binario de tu perfil.',
    github:'Actualización desde GitHub',githubKicker:'Busca una release pública para este perfil y verifica tamaño y SHA-256.',checkUpdates:'Comprobar actualizaciones',installUpdate:'Instalar actualización',neverChecked:'Nunca comprobado',readingVersion:'Leyendo versión instalada…',installed:'Instalado: {version} · {profile}',githubHint:'Releases de felipedelpozo/adblock. La instalación conserva WiFi, listas y ajustes.',
    footerQueries:'Últimas 64 consultas:',footerHint:'historial reciente; se vacía al reiniciar la placa. Los contadores de esta sesión siguen la misma regla.',
    active:'Bloqueo activo',paused:'Bloqueo en pausa',activeNote:'Las consultas coincidentes se rechazan ahora',resumeIn:'Se reanuda en {seconds} s',pausedIndefinitely:'Pausa indefinida; reactiva cuando quieras',
    noMatches:'No hay coincidencias para este filtro.',noBlocked:'No hay consultas bloqueadas todavía.',matchesOne:'coincidencia · mostrando',matchesMany:'coincidencias · mostrando',retained:'retenidas',updatedAt:'Actualizado {time}',
    offlineDevice:'Dispositivo sin conexión',offlineRetry:'No se pudo actualizar el estado; revisando de nuevo…',offlineHistory:'No se pudo cargar el historial. Reintentando…',
    invalidList:'La solicitud no es válida. Revisa el perfil o el dominio.',expired:'La sesión del dashboard ya no es válida. Recarga la página.',listBusy:'La lista ya se está actualizando. Espera a que termine.',listLoad:'No se pudo cargar el estado de las listas. Reintentando…',listStart:'No se pudo iniciar la actualización de la lista.',requestAccepted:'Solicitud aceptada; esperando aplicación…',toggleFailed:'No se pudo cambiar el estado',
    invalidDomain:'El dominio no es válido.',allowExpired:'La sesión del dashboard ya no es válida. Recarga la página.',allowMissing:'Ese dominio ya no está en permitidos.',allowFull:'No se pudo permitir: ya está permitido o la lista ha alcanzado el máximo de 200 dominios.',allowFailed:'No se pudo cambiar la lista de permitidos.',
    changing:'Cambiando…',addDomainFailed:'No se pudo añadir el dominio',removeDomainFailed:'No se pudo quitar el dominio',changeClientFailed:'No se pudo cambiar el cliente',saved:'Guardado',saveFailed:'No se pudo guardar',downloading:'Descargando…',downloadFailed:'Descarga fallida',selectFile:'Selecciona un archivo',uploading:'Subiendo {size} MB…',uploadFailed:'✗ Falló la subida',blocklistUpdated:'✓ Blocklist actualizada',blocklistRejected:'✗ Blocklist rechazada',restarting:'✓ Reiniciando; reconecta en unos 15 s',firmwareRejected:'✗ Firmware rechazado',
    confirmWifi:'¿Cambiar la Wi-Fi? El dispositivo reiniciará en modo configuración y el bloqueo se interrumpirá mientras eliges la red. Las listas, las excepciones y la Wi-Fi anterior se conservan.',preparingWifi:'Preparando la configuración…',wifiStarted:'Configuración iniciada. Conecta a la red del dispositivo o abre su página de configuración.',configuringWifi:'Configurando Wi-Fi',wifiResumeNote:'El bloqueo volverá al terminar la configuración.',wifiConflict:'Espera a que termine la actualización de listas o firmware.',wifiForbidden:'Recarga la página para volver a intentarlo.',wifiFailed:'No se pudo confirmar el reinicio. Si se ha desconectado, sigue las instrucciones de configuración; si sigue en línea, vuelve a intentarlo.',
    languageSaving:'Guardando idioma…',languageSaved:'Idioma actualizado',languageFailed:'No se pudo guardar el idioma. Se ha restaurado el idioma anterior.',invalidLanguage:'No se pudo confirmar el idioma seleccionado.',confirmGithub:'¿Instalar {version} en este dispositivo? Reiniciará al verificar el firmware; conservará WiFi, listas y ajustes.',installing:'Iniciando instalación…',checkingReleases:'Comprobando releases…',installingDownload:'Descargando y verificando…',checkingStarted:'Comprobación en curso…',githubFailed:'No se pudo iniciar la operación; vuelve a comprobar',
    typeA:'A',typeAAAA:'AAAA',typeOther:'TYPE {value}',reasonClient:'cliente',reasonCustom:'propio',reasonBlocklist:'blocklist',clientBlockedTitle:'Desbloquea el cliente en Clientes',seconds:'hace {value} s',minutes:'hace {value} min',hours:'hace {value} h',days:'hace {value} d'
  },
  en:{
    title:'AdBlock · Console',languageLabel:'Language',eyebrow:'Network protection',sub:'See what is blocked and control your network protection.',
    connecting:'Connecting…',device:'device',checkingBlocking:'Checking blocking…',syncingDevice:'Syncing with the device',loading:'Loading…',pauseDuration:'Pause duration',pause30:'30 seconds',pause5:'5 minutes',pause30m:'30 minutes',pauseUntil:'Until reactivated',pause:'Pause',resume:'Resume',
    system:'System status',activity:'ACTIVITY',updating:'Updating…',blockedQueries:'Blocked queries',blockedQueriesKicker:'Latest requests rejected by the device',
    filterLog:'Filter by domain or client',searchPlaceholder:'Search domain or IP…',domain:'Domain',client:'Client',type:'Type',reason:'Reason',age:'Age',action:'Action',
    loadingHistory:'Loading history…',previous:'Previous',next:'Next',clients:'Clients',clientsKicker:'Activity observed since the last boot',clientIp:'IP',clientMac:'MAC',blockedShort:'Blocked',allowedShort:'Allowed',
    customDomains:'Custom domains',customDomainsKicker:'Rules added manually',domainToBlock:'Domain to block',block:'Block',domainPlaceholder:'ads.example.com',
    noClients:'No clients yet',blockedBadge:'BLOCKED',unblockClient:'Unblock',blockClient:'Block',remove:'Remove',noCustom:'There are no custom domains yet.',
    lists:'BLOCKLISTS',listsIntro:'The active profile stays in place until the new list finishes applying.',protectionProfile:'Protection profile',
    profileKicker:'Choose HaGeZi coverage and review the change before applying it.',selectedProfile:'Selected profile',
    customProfile:'Custom · current list',lightProfile:'Light · HaGeZi Light',balancedProfile:'Balanced · HaGeZi PRO (recommended)',strictProfile:'Strict · HaGeZi PRO++ (may break sites)',
    applyProfile:'Apply profile',refreshList:'Update list now',listActive:'Active: {value}',listSelected:'Selected: {value}',profileProgress:'Progress: {value}% · active profile remains {profile}',
    applied:'List applied: {profile}',customListPreserved:'The custom list keeps the existing configuration.',customListHint:'Custom uses the binary upload and URL configured below; choosing a profile does not change the list until checking and applying finishes.',
    preparing:'List ready',noAllow:'There are no saved exceptions yet.',allowDomains:'Allowed domains',allowDomainsKicker:'Persistent exceptions for this network',allowNote:'Allow this domain and its subdomains even when they appear in a blocklist or custom rule. Client bans still take priority.',
    domainToAllow:'Domain to allow',allow:'Allow domain',allowPlaceholder:'example.com',allowCount:'{count} / 200',allowing:'Saving…',removing:'Removing…',allowed:'Domain allowed',allowRemoved:'Exception removed',
    settings:'SETTINGS',settingsIntro:'Changes are applied to the device when saved.',wifiAccess:'Wi-Fi and access',wifiKicker:'Change networks while keeping lists, exceptions and settings.',
    currentNetwork:'Current network: {ssid}',queryingNetwork:'Checking network…',changeWifi:'Change Wi-Fi',wifiSetupInstructions:'Connect to the {ap} network and open 192.168.4.1 to choose the new Wi-Fi.',
    wifiOldHint:'The previous network stays saved until the new connection is verified. Cancel from the setup page to return to it.',wifi24Hint:'Use a 2.4 GHz network. If the device IP changes, update the DNS address in your router or devices.',
    localBlocklist:'Custom · Local blocklist',localBlocklistKicker:'Upload a compiled binary list without USB.',blocklistFile:'blocklist.bin file',uploadBlocklist:'Upload blocklist',
    buildHint:'Generate blocklist.bin with tools/build_blocklist.py.',remoteUpdate:'Custom · Remote update',remoteKicker:'Download a precompiled blocklist on a schedule.',
    blocklistUrl:'Blocklist URL',interval:'Interval in hours',save:'Save',downloadNow:'Download now',remoteHint:'The device keeps the latest response here; an empty URL disables custom downloads. The interval is also used for HaGeZi profiles.',
    firmware:'Firmware · OTA',firmwareKicker:'The device validates the binary and restarts on the new version.',firmwareFile:'Firmware file',flashFirmware:'Flash firmware',firmwareHint:'Select firmware.bin or the binary for your profile.',
    github:'GitHub update',githubKicker:'Find a public release for this profile and verify its size and SHA-256.',checkUpdates:'Check for updates',installUpdate:'Install update',neverChecked:'Never checked',readingVersion:'Reading installed version…',installed:'Installed: {version} · {profile}',githubHint:'Releases from felipedelpozo/adblock. Installation preserves Wi-Fi, lists and settings.',
    footerQueries:'Last 64 queries:',footerHint:'recent history; it is cleared when the board restarts. Session counters follow the same rule.',
    active:'Blocking active',paused:'Blocking paused',activeNote:'Matching queries are being rejected now',resumeIn:'Resumes in {seconds} s',pausedIndefinitely:'Paused indefinitely; reactivate when you want',
    noMatches:'No matches for this filter.',noBlocked:'No blocked queries yet.',matchesOne:'match · showing',matchesMany:'matches · showing',retained:'retained',updatedAt:'Updated {time}',
    offlineDevice:'Device offline',offlineRetry:'Could not update status; checking again…',offlineHistory:'Could not load history. Retrying…',
    invalidList:'The request is invalid. Check the profile or domain.',expired:'The dashboard session is no longer valid. Reload the page.',listBusy:'The list is already updating. Wait for it to finish.',listLoad:'Could not load list status. Retrying…',listStart:'Could not start the list update.',requestAccepted:'Request accepted; waiting for it to apply…',toggleFailed:'Could not change the blocking state',
    invalidDomain:'The domain is invalid.',allowExpired:'The dashboard session is no longer valid. Reload the page.',allowMissing:'That domain is no longer allowed.',allowFull:'Could not allow it: it is already allowed or the list has reached the 200-domain limit.',allowFailed:'Could not change the allowed list.',
    changing:'Changing…',addDomainFailed:'Could not add the domain',removeDomainFailed:'Could not remove the domain',changeClientFailed:'Could not change the client',saved:'Saved',saveFailed:'Could not save',downloading:'Downloading…',downloadFailed:'Download failed',selectFile:'Select a file',uploading:'Uploading {size} MB…',uploadFailed:'✗ Upload failed',blocklistUpdated:'✓ Blocklist updated',blocklistRejected:'✗ Blocklist rejected',restarting:'✓ Restarting; reconnect in about 15 s',firmwareRejected:'✗ Firmware rejected',
    confirmWifi:'Change Wi-Fi? The device will restart in setup mode and blocking will pause while you choose a network. Lists, exceptions and the previous Wi-Fi are preserved.',preparingWifi:'Preparing setup…',wifiStarted:'Setup started. Connect to the device network or open its setup page.',configuringWifi:'Configuring Wi-Fi',wifiResumeNote:'Blocking will resume when setup finishes.',wifiConflict:'Wait for the list or firmware update to finish.',wifiForbidden:'Reload the page to try again.',wifiFailed:'Could not confirm the restart. If the device disconnected, follow the setup instructions; if it is still online, try again.',
    languageSaving:'Saving language…',languageSaved:'Language updated',languageFailed:'Could not save the language. The previous language was restored.',invalidLanguage:'Could not confirm the selected language.',confirmGithub:'Install {version} on this device? It will restart after verifying the firmware; Wi-Fi, lists and settings will be preserved.',installing:'Starting installation…',checkingReleases:'Checking releases…',installingDownload:'Downloading and verifying…',checkingStarted:'Check in progress…',githubFailed:'Could not start the operation; check again',
    typeA:'A',typeAAAA:'AAAA',typeOther:'TYPE {value}',reasonClient:'client',reasonCustom:'custom',reasonBlocklist:'blocklist',clientBlockedTitle:'Unblock the client in Clients',seconds:'{value} s ago',minutes:'{value} min ago',hours:'{value} h ago',days:'{value} d ago'
  }
};
state.language='es';state.languagePending=false;state.languageEpoch=0;state.applyingLanguage=false;state.latestStats=null;state.latestLists=null;state.latestLog=null;
function languageValue(value){return value==='en'?'en':'es'}
function t(key,values){const dict=I18N[state.language]||I18N.es;let value=dict[key]||I18N.es[key]||key;Object.keys(values||{}).forEach(name=>{value=value.replace(new RegExp('\\{'+name+'\\}','g'),()=>String(values[name]))});return value}
function locale(){return state.language==='en'?'en-US':'es-ES'}
function fmt(value){return Number(value||0).toLocaleString(locale())}
function staticText(selector,key){if(!document.querySelectorAll)return;document.querySelectorAll(selector).forEach(node=>{node.textContent=t(key)})}
function staticTexts(selector,keys){if(!document.querySelectorAll)return;document.querySelectorAll(selector).forEach((node,index)=>{if(keys[index])node.textContent=t(keys[index])})}
function applyStaticLanguage(){if(document.documentElement)document.documentElement.lang=state.language;if(document.title!==undefined)document.title=t('title');
  staticText('.eyebrow','eyebrow');staticText('.sub','sub');staticText('#languageLabel','languageLabel');staticText('#host','connecting');staticText('#blockstate','checkingBlocking');staticText('#blocknote','syncingDevice');staticText('#pausebtn','pause');staticText('#pausedur option[value=\"30\"]','pause30');staticText('#pausedur option[value=\"300\"]','pause5');staticText('#pausedur option[value=\"1800\"]','pause30m');staticText('#pausedur option[value=\"0\"]','pauseUntil');if(document.querySelector){const sys=document.querySelector('#sys');if(sys&&sys.setAttribute)sys.setAttribute('aria-label',t('system'))}
  staticTexts('.section-label h2',['activity','lists','settings']);staticTexts('.section-label p',['updating','listsIntro','settingsIntro']);
  staticTexts('.panel-title',['blockedQueries','clients','customDomains','protectionProfile','allowDomains','wifiAccess','localBlocklist','remoteUpdate','firmware','github']);
  staticTexts('.panel-kicker',['blockedQueriesKicker','clientsKicker','customDomainsKicker','profileKicker','allowDomainsKicker','wifiKicker','localBlocklistKicker','remoteKicker','firmwareKicker','githubKicker']);
  staticTexts('.hint',['customListHint','wifiOldHint','wifi24Hint','buildHint','remoteHint','firmwareHint','readingVersion','githubHint']);staticText('.allow-note','allowNote');staticText('#listsProgressText','customListPreserved');
  staticTexts('.layout > section.panel table thead th',['domain','client','type','reason','age','action']);staticTexts('.client-table thead th',['clientIp','clientMac','blockedShort','allowedShort','action']);
  staticText('#logSearch','filterLog');$('logSearch').placeholder=t('searchPlaceholder');
  staticText('#logMeta','loadingHistory');staticText('#prevPage','previous');staticText('#nextPage','next');staticText('#dom','domainToBlock');$('dom').placeholder=t('domainPlaceholder');staticText('#domainForm button','block');
  staticTexts('#profileSelect option',['customProfile','lightProfile','balancedProfile','strictProfile']);staticText('label[for="profileSelect"]','selectedProfile');staticText('#profileApply','applyProfile');staticText('#listsCheck','refreshList');staticText('#allowDomain','domainToAllow');$('allowDomain').placeholder=t('allowPlaceholder');staticText('#allowAdd','allow');
  $('allowCount').textContent=t('allowCount',{count:0});staticText('#listsCount','loading');$('listsActive').textContent=t('listActive',{value:'—'});$('listsSelected').textContent=t('listSelected',{value:'—'});staticText('#listsStatus','loading');staticText('#lastRefresh','updating');staticText('#wifiNetwork','queryingNetwork');staticText('#wifiChange','changeWifi');staticText('#blf','blocklistFile');staticText('#uploadForm button','uploadBlocklist');staticText('#uurl','blocklistUrl');$('uurl').placeholder='https://host/blocklist.bin';staticText('#uiv','interval');staticText('#updateForm button[type=\"submit\"]','save');staticText('#fetchNow','downloadNow');
  staticText('#fwb','firmwareFile');staticText('#firmwareForm button','flashFirmware');staticText('#githubCheck','checkUpdates');staticText('#githubInstall','installUpdate');staticText('#githubStatus','neverChecked');staticText('.status label.sr-only','pauseDuration');staticText('label[for=\"logSearch\"]','filterLog');staticText('label[for=\"dom\"]','domainToBlock');staticText('label[for=\"allowDomain\"]','domainToAllow');staticText('label[for=\"blf\"]','blocklistFile');staticText('label[for=\"uurl\"]','blocklistUrl');staticText('label[for=\"uiv\"]','interval');staticText('label[for=\"fwb\"]','firmwareFile');staticTexts('table span.sr-only',['action','action']);
  if(document.querySelector){const instruction=document.querySelector('#wifiInstructions p:first-child');if(instruction&&instruction.childNodes&&instruction.childNodes.length>=5){instruction.childNodes[0].textContent=state.language==='en'?'Connect to the ':'Conecta a la red ';instruction.childNodes[2].textContent=state.language==='en'?' network and open ':' y abre ';instruction.childNodes[4].textContent=state.language==='en'?' to choose the new Wi-Fi.':' para elegir la nueva Wi-Fi.'}const footer=document.querySelector('p.hint[style*="margin-top"]');if(footer&&footer.childNodes&&footer.childNodes.length>=2){footer.childNodes[0].textContent=t('footerQueries');footer.childNodes[1].textContent=' '+t('footerHint')}}staticText('#wifiInstructions p:nth-child(2)','wifiOldHint');
}
function updateLanguageControl(){const select=$('languageSelect');if(select){select.value=state.language;select.disabled=!state.githubNonce||state.offline||state.languagePending||state.wifiPending||state.wifiReconfiguring}}
function applyLanguage(value){const next=languageValue(value);if(state.applyingLanguage&&state.language===next)return;state.language=next;state.applyingLanguage=true;applyStaticLanguage();updateLanguageControl();if(state.latestStats){renderStatus(state.latestStats);renderMetrics(state.latestStats);renderClients(state.latestStats.clients);renderCustom(state.latestStats.custom);renderFirmware(state.latestStats);renderWifi(state.latestStats)}if(state.latestLists)renderLists(state.latestLists);if(state.latestLog)renderLog(state.latestLog);state.applyingLanguage=false}
function syncStatsLanguage(value){const incoming=languageValue(value);if(!state.languagePending&&!state.applyingLanguage&&incoming!==state.language)applyLanguage(incoming)}
function renderMetrics(s,skipLanguageSync){state.latestStats=s;if(!skipLanguageSync)syncStatsLanguage(s.language);const clients=Array.isArray(s.clients)?s.clients:[];const sys=$('sys');clear(sys);sys.append(metric(t('blocked'),fmt(s.blocked),'warn'),metric(t('allowed'),fmt(s.allowed),'good'),metric(t('domains'),fmt(s.domains)),metric(t('clientsObserved'),fmt(clients.length)),metric('WiFi',s.rssi+' dBm'),metric(t('temperature'),fmt(s.temp)+' °C'),metric(t('freeRam'),Math.round(s.heap/1024)+' KB'),metric(t('uptime'),s.uptime))}
I18N.es.blocked='Bloqueadas';I18N.en.blocked='Blocked';I18N.es.allowed='Permitidas';I18N.en.allowed='Allowed';I18N.es.domains='Dominios en blocklist';I18N.en.domains='Blocklist domains';I18N.es.clientsObserved='Clientes observados';I18N.en.clientsObserved='Observed clients';I18N.es.temperature='Temperatura';I18N.en.temperature='Temperature';I18N.es.freeRam='RAM libre';I18N.en.freeRam='Free RAM';I18N.es.uptime='Uptime';I18N.en.uptime='Uptime';
function renderStatus(s){const on=s.blocking!==false;const bar=$('blockbar');bar.classList.toggle('paused',!on);$('blockdot').textContent=on?'✓':'Ⅱ';$('blockstate').textContent=on?t('active'):t('paused');$('blockstate').dataset.on=on?'1':'0';$('blocknote').textContent=on?t('activeNote'):(s.resumeIn>0?t('resumeIn',{seconds:s.resumeIn}):t('pausedIndefinitely'));$('pausebtn').textContent=on?t('pause'):t('resume');$('pausebtn').classList.toggle('primary',on);$('pausebtn').disabled=false;$('pausedur').hidden=!on}
function renderClients(clients){const body=$('clientBody');clear(body);const rows=(clients||[]).slice().sort((a,b)=>(b.blocked+b.allowed)-(a.blocked+a.allowed));if(!rows.length){const row=el('tr');const cell=el('td','empty',t('noClients'));cell.colSpan=5;row.append(cell);body.append(row);return}rows.forEach(client=>{const row=el('tr');const ip=el('td','client',client.ip);if(client.banned)ip.append(el('span','badge',t('blockedBadge')));row.append(ip,el('td','mono client',client.mac),el('td','num block-num',fmt(client.blocked)),el('td','num allow-num',fmt(client.allowed)));const action=el('button','quiet danger',client.banned?t('unblockClient'):t('blockClient'));action.type='button';action.dataset.ip=client.ip;const actionCell=el('td');actionCell.append(action);row.append(actionCell);body.append(row)})}
function renderCustom(domains){const body=$('customBody');clear(body);if(!domains||!domains.length){body.append(el('p','empty',t('noCustom')));return}domains.forEach(domain=>{const row=el('div','custom-row');row.append(el('span','domain',domain));const button=el('button','quiet danger',t('remove'));button.type='button';button.dataset.domain=domain;row.append(button);body.append(row)})}
const PROFILE_NAMES_I18N={custom:'customProfile',light:'lightProfile',balanced:'balancedProfile',strict:'strictProfile'};
function profileValue(value){return Object.prototype.hasOwnProperty.call(PROFILE_NAMES_I18N,value)?value:'custom'}
function profileLabel(value){return t(PROFILE_NAMES_I18N[profileValue(value)])}
function listsErrorMessage(error,fallback){const status=error&&error.status;if(status===400)return t('invalidList');if(status===403)return t('expired');if(status===409)return t('listBusy');return fallback}
function allowlistErrorMessage(error,remove){const status=error&&error.status;if(status===400)return t('invalidDomain');if(status===403)return t('allowExpired');if(status===404||status===409)return remove?t('allowMissing'):t('allowFull');return t('allowFailed')}
function renderAllowed(domains){const body=$('allowBody');clear(body);const rows=(Array.isArray(domains)?domains:[]).slice(0,200);state.allowed=rows.slice();$('allowCount').textContent=t('allowCount',{count:fmt(rows.length)});if(!rows.length){body.append(el('p','empty',t('noAllow')));return}rows.forEach(domain=>{const row=el('div','allow-row');row.append(el('span','domain',domain));const button=el('button','quiet danger',t('remove'));button.type='button';button.dataset.allowDomain=domain;button.disabled=state.allowlistBusy||state.listsBusy||state.listsAction||!state.listsReady;row.append(button);body.append(row)})}
function renderLists(data){state.latestLists=data;const selected=profileValue(data.selectedProfile);const applied=profileValue(data.appliedProfile);const busy=!!data.busy;const progress=Math.max(0,Math.min(100,Number(data.progress)||0));const select=$('profileSelect');state.listsAppliedProfile=applied;if(!state.listsProfileDirty||selected===state.listsProfileDraft&&!busy){state.listsProfileDraft=selected;state.listsProfileDirty=false;select.value=selected}const domains=Math.max(0,Number(data.domains)||0);$('listsCount').textContent=fmt(domains)+' '+(state.language==='en'?'domains':'dominios');$('listsActive').textContent=t('listActive',{value:profileLabel(applied)});$('listsSelected').textContent=t('listSelected',{value:profileLabel(state.listsProfileDraft||selected)});$('listsStatus').textContent=data.status|| (busy?t('updating'):t('preparing'));$('listsProgress').value=progress;$('listsProgress').hidden=!busy&&progress<=0;$('listsProgressText').textContent=busy?t('profileProgress',{value:progress,profile:profileLabel(applied)}):progress>=100?t('applied',{profile:profileLabel(applied)}):t('customListPreserved');if(Array.isArray(data.allowed))renderAllowed(data.allowed);state.listsBusy=busy;updateListsControls()}
function queryType(type){const n=Number(type);return n===1?t('typeA'):n===28?t('typeAAAA'):t('typeOther',{value:Number.isFinite(n)?n:'?'})}
function reasonLabel(reason){return reason==='client'?t('reasonClient'):reason==='custom'?t('reasonCustom'):t('reasonBlocklist')}
function age(seconds){const s=Math.max(0,Number(seconds)||0);if(s<60)return t('seconds',{value:Math.round(s)});if(s<3600)return t('minutes',{value:Math.floor(s/60)});if(s<86400)return t('hours',{value:Math.floor(s/3600)});return t('days',{value:Math.floor(s/86400)})}
function renderLog(data){state.latestLog=data;const body=$('logBody');clear(body);const entries=data.entries||[];if(!entries.length){const row=el('tr');const cell=el('td','empty',state.logQuery?t('noMatches'):t('noBlocked'));cell.colSpan=6;row.append(cell);body.append(row)}else entries.forEach(entry=>{const row=el('tr');row.append(el('td','domain',entry.domain),el('td','client',entry.client),el('td','mono client',queryType(entry.type)));const kind=entry.reason==='custom'?'custom':entry.reason==='client'?'client':'';const reason=el('span','reason '+kind,reasonLabel(entry.reason));const reasonCell=el('td');reasonCell.append(reason);const actionCell=el('td');const allow=el('button','quiet log-action',t('allow'));allow.type='button';allow.dataset.allowDomain=String(entry.domain||'');const clientBanned=entry.reason==='client';allow.disabled=clientBanned||!state.listsReady||state.allowlistBusy||state.listsBusy;if(clientBanned)allow.title=t('clientBlockedTitle');actionCell.append(allow);row.append(reasonCell,el('td','age',age(entry.ageSeconds)),actionCell);body.append(row)});const start=entries.length?data.offset+1:0;const end=data.offset+entries.length;$('logMeta').textContent=fmt(data.count)+(data.count===1?' '+t('matchesOne')+' ':' '+t('matchesMany')+' ')+fmt(start)+'–'+fmt(end)+' '+(state.language==='en'?'of':'de')+' '+fmt(data.total)+' '+t('retained');$('prevPage').disabled=data.offset<=0;$('nextPage').disabled=!data.more}
function renderFirmware(s){state.githubNonce=s.githubNonce||'';state.githubVersion=s.githubVersion||'';state.githubCanInstall=!!s.githubCanInstall;$('fwIdentity').textContent=s.fwVersion?t('installed',{version:s.fwVersion,profile:s.fwProfile||'—'}):t('readingVersion');$('githubStatus').textContent=(s.githubStatus||t('neverChecked'))+(s.githubBusy&&s.githubProgress>0?' · '+s.githubProgress+'%':'');$('githubCheck').disabled=!state.githubNonce||!!s.githubBusy||state.githubPending;$('githubInstall').disabled=!state.githubNonce||!state.githubCanInstall||!!s.githubBusy||state.githubPending;$('githubInstall').textContent=state.githubCanInstall?t('installUpdate')+' '+state.githubVersion:t('installUpdate');state.wifiFirmwareBusy=!!s.githubBusy;updateWifiControls()}
function renderWifi(s){state.wifiAp=typeof s.wifiSetupAp==='string'?s.wifiSetupAp:'';$('wifiNetwork').textContent=s.wifiSsid?t('currentNetwork',{ssid:s.wifiSsid}):t('queryingNetwork');$('wifiAp').textContent=state.wifiAp||'C3-AdBlock-XXXX';updateWifiControls()}
function setOffline(isOffline){state.offline=isOffline;const connection=$('connection');connection.classList.toggle('offline',isOffline);$('host').textContent=isOffline?t('offlineDevice'):'@ '+(connection.dataset.ip||t('device'));connection.querySelector('.dot').classList.toggle('off',isOffline);if(isOffline){$('githubCheck').disabled=true;$('githubInstall').disabled=true}updateWifiControls()}
function setLanguageStatus(message,error){const node=$('languageStatus');if(node){node.textContent=message;node.classList.toggle('offline',!!error)}}
async function saveLanguage(value){const next=languageValue(value);if(state.languagePending||state.offline||state.wifiReconfiguring||!state.githubNonce)return;const previous=state.language;state.languagePending=true;state.languageEpoch++;applyLanguage(next);setLanguageStatus(t('languageSaving'));updateLanguageControl();try{const response=await request('/language?lang='+next,{method:'POST',headers:{'X-CSRF-Token':state.githubNonce}});const data=await response.json();if(data.language!==next)throw new Error('Invalid language response');state.languagePending=false;applyLanguage(next);setLanguageStatus(t('languageSaved'));updateLanguageControl()}catch(error){state.languagePending=false;applyLanguage(previous);setLanguageStatus(t('languageFailed'),true);updateLanguageControl()}}
async function changeWifi(){if($('wifiChange').disabled||state.wifiPending||state.wifiReconfiguring)return;if(!confirm(t('confirmWifi')))return;state.wifiPending=true;$('wifiInstructions').hidden=false;updateWifiControls();actionStatus($('wifiStatus'),t('preparingWifi'));try{const response=await request('/wifi/setup',{method:'POST',headers:{'X-CSRF-Token':state.githubNonce}});const data=await response.json();if(data.ap)$('wifiAp').textContent=String(data.ap);state.wifiReconfiguring=true;actionStatus($('wifiStatus'),t('wifiStarted'));$('blockstate').textContent=t('configuringWifi');$('blocknote').textContent=t('wifiResumeNote');$('pausebtn').disabled=true;updateListsControls();$('githubCheck').disabled=true;$('githubInstall').disabled=true}catch(error){const message=error.status===409?t('wifiConflict'):error.status===403?t('wifiForbidden'):t('wifiFailed');actionStatus($('wifiStatus'),message,true)}finally{state.wifiPending=false;updateWifiControls()}}
async function togglePause(){const button=$('pausebtn');button.disabled=true;try{const path=$('blockstate').dataset.on==='1'?'/pause?s='+$('pausedur').value:'/resume';await request(path);await loadStats()}catch(_){actionStatus($('blocknote'),t('toggleFailed'),true)}finally{button.disabled=false}}
async function githubAction(install){if(state.githubPending||!state.githubNonce||(install&&!state.githubCanInstall))return;const version=state.githubVersion;if(install&&!confirm(t('confirmGithub',{version})))return;state.githubPending=true;updateWifiControls();$('githubCheck').disabled=true;$('githubInstall').disabled=true;actionStatus($('githubStatus'),install?t('installing'):t('checkingReleases'));try{await request(install?'/github/install?v='+encodeURIComponent(version):'/github/check',{method:'POST',headers:{'X-CSRF-Token':state.githubNonce}});actionStatus($('githubStatus'),install?t('installingDownload'):t('checkingStarted'))}catch(_){actionStatus($('githubStatus'),t('githubFailed'),true)}finally{state.githubPending=false;updateWifiControls();setTimeout(loadStats,500)}}
function applyProfile(){const value=profileValue($('profileSelect').value);if(value==='custom')return;state.listsProfileDraft=value;listsAction('/lists/profile?p='+encodeURIComponent(value),t('listStart'))}
function checkLists(){if(state.listsProfileDraft==='custom')return;listsAction('/lists/check',t('checkingStarted'))}
function localizeStaticAfterStartup(){applyLanguage(state.language);updateLanguageControl()}
$('languageSelect').addEventListener('change',event=>saveLanguage(event.target.value));localizeStaticAfterStartup();
$('wifiChange').addEventListener('click',changeWifi);
$('pausebtn').addEventListener('click',togglePause);$('logSearch').addEventListener('input',event=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>{state.logQuery=event.target.value.trim().slice(0,63);state.logPage=0;requestLog()},280)});$('prevPage').addEventListener('click',()=>{if(state.logPage){state.logPage--;requestLog()}});$('nextPage').addEventListener('click',()=>{if(!$('nextPage').disabled){state.logPage++;requestLog()}});
$('clientBody').addEventListener('click',async event=>{const button=event.target.closest('button[data-ip]');if(!button)return;button.disabled=true;try{await request('/ban?ip='+encodeURIComponent(button.dataset.ip));await loadStats()}catch(_){actionStatus($('blocknote'),t('changeClientFailed'),true)}finally{button.disabled=false}});
$('customBody').addEventListener('click',async event=>{const button=event.target.closest('button[data-domain]');if(!button)return;button.disabled=true;try{await request('/unblock?d='+encodeURIComponent(button.dataset.domain));await loadStats()}catch(_){actionStatus($('blocknote'),t('removeDomainFailed'),true)}finally{button.disabled=false}});
$('domainForm').addEventListener('submit',async event=>{event.preventDefault();const input=$('dom'),domain=input.value.trim();if(!domain)return;const button=event.submitter||event.target.querySelector('button');button.disabled=true;try{await request('/addblock?d='+encodeURIComponent(domain));input.value='';await loadStats()}catch(_){actionStatus($('blocknote'),t('addDomainFailed'),true)}finally{button.disabled=false}});
$('uurl').addEventListener('input',()=>{state.updateDirty=true});$('uiv').addEventListener('input',()=>{state.updateDirty=true});$('updateForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter||event.target.querySelector('button');button.disabled=true;try{const hours=Math.max(1,parseInt($('uiv').value,10)||24);await request('/setupdate?u='+encodeURIComponent($('uurl').value.trim())+'&h='+hours);state.updateDirty=false;actionStatus($('ustat'),t('saved'));await loadStats()}catch(_){actionStatus($('ustat'),t('saveFailed'),true)}finally{button.disabled=false}});
$('fetchNow').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;actionStatus($('ustat'),t('downloading'));try{const text=await(await request('/fetchnow')).text();actionStatus($('ustat'),text);await loadStats()}catch(_){actionStatus($('ustat'),t('downloadFailed'),true)}finally{button.disabled=false}});
function uploadOptions(url,data){const options={method:'POST',body:data};if(url==='/upload')options.headers={'X-CSRF-Token':state.listsNonce};return options}
async function upload(formId,inputId,statusId,url,success,failure){$(formId).addEventListener('submit',async event=>{event.preventDefault();const input=$(inputId),file=input.files[0],status=$(statusId),button=event.submitter||event.target.querySelector('button');if(!file){actionStatus(status,t('selectFile'),true);return}button.disabled=true;actionStatus(status,t('uploading',{size:(file.size/1048576).toFixed(2)}));const data=new FormData();data.append('f',file);try{const response=await request(url,uploadOptions(url,data));actionStatus(status,success(response.ok));input.value='';setTimeout(loadStats,600)}catch(_){actionStatus(status,failure,true)}finally{button.disabled=false}})}
upload('uploadForm','blf','upmsg','/upload',ok=>ok?t('blocklistUpdated'):t('blocklistRejected'),t('uploadFailed'));upload('firmwareForm','fwb','fwmsg','/update',ok=>ok?t('restarting'):t('firmwareRejected'),t('uploadFailed'));
$('githubCheck').addEventListener('click',()=>githubAction(false));$('githubInstall').addEventListener('click',()=>githubAction(true));
$('profileSelect').addEventListener('change',event=>{if(!state.listsReady||state.listsBusy)return;state.listsProfileDraft=profileValue(event.target.value);state.listsProfileDirty=true;$('listsSelected').textContent=t('listSelected',{value:profileLabel(state.listsProfileDraft)});updateListsControls()});$('profileApply').addEventListener('click',applyProfile);$('listsCheck').addEventListener('click',checkLists);$('allowlistForm').addEventListener('submit',event=>{event.preventDefault();changeAllowlist($('allowDomain').value,false)});$('allowBody').addEventListener('click',event=>{const button=event.target.closest('button[data-allow-domain]');if(button)changeAllowlist(button.dataset.allowDomain,true)});$('logBody').addEventListener('click',event=>{const button=event.target.closest('button[data-allow-domain]');if(button)changeAllowlist(button.dataset.allowDomain,false)});
setTimeout(loadLists,0);loadStats();requestLog();setInterval(loadStats,4000);setInterval(()=>{if(document.activeElement!==$('logSearch'))requestLog()},4000);setInterval(()=>{if(!state.listsAction&&!state.listsFetchBusy)loadLists()},4000);
</script></body></html>)HTML";
