#pragma once
// Dashboard HTML for the C3 AdBlocker web UI, kept in its own header so the
// Arduino IDE preprocessor doesn't choke on the inlined markup (issue #6).

const char PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f8f7">
<title>AdBlock · Consola</title><style>
:root{--ink:#102b34;--muted:#64777c;--line:#d8e2e1;--paper:#f6f8f7;--panel:#fff;--teal:#087f78;--teal-dark:#05645f;--teal-soft:#dff3ef;--amber:#b56a13;--red:#b5443b;--shadow:0 12px 30px rgba(16,43,52,.07);--radius:14px}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.01em}button,input,select{font:inherit}button{border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--ink);padding:8px 12px;cursor:pointer;transition:background .15s,border-color .15s,transform .15s}button:hover{border-color:#9db5b2;background:#f1f7f5}button:active{transform:translateY(1px)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid rgba(8,127,120,.25);outline-offset:2px}.primary{background:var(--teal);border-color:var(--teal);color:#fff;font-weight:650}.primary:hover{background:var(--teal-dark);border-color:var(--teal-dark)}.quiet{padding:6px 9px;color:var(--muted);background:transparent}.danger{color:var(--red)}.wrap{width:min(1160px,calc(100% - 32px));margin:0 auto;padding:24px 0 56px}
.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:26px}.eyebrow{color:var(--teal);font-size:11px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.brand{margin:4px 0 3px;font-size:clamp(24px,4vw,35px);letter-spacing:-.04em;line-height:1.1}.sub{margin:0;color:var(--muted)}.host{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;padding:9px 11px;border:1px solid var(--line);background:#fff;border-radius:999px;white-space:nowrap}.dot{width:8px;height:8px;border-radius:99px;background:var(--teal);box-shadow:0 0 0 4px var(--teal-soft)}.dot.off{background:var(--red);box-shadow:0 0 0 4px #fae6e3}
.status{display:flex;align-items:center;gap:14px;padding:16px 18px;margin-bottom:18px;background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--teal);border-radius:var(--radius);box-shadow:var(--shadow)}.status.paused{border-left-color:var(--amber)}.shield{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:var(--teal-soft);font-size:19px}.paused .shield{background:#fff1da}.status-copy{flex:1;min-width:0}.status-title{display:block;font-size:15px;font-weight:750}.status-note{display:block;color:var(--muted);font-size:12px;margin-top:2px}.status-actions{display:flex;align-items:center;gap:8px}.status select{border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);padding:8px}.status select[hidden]{display:none}
.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:22px}.metric{padding:15px 16px;background:var(--panel);border:1px solid var(--line);border-radius:12px}.metric-value{font-size:24px;font-weight:760;letter-spacing:-.04em;line-height:1.1}.metric-label{color:var(--muted);font-size:12px;margin-top:6px}.metric-value.good{color:var(--teal)}.metric-value.warn{color:var(--amber)}
.section-label{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin:24px 0 9px}.section-label h2{margin:0;font-size:14px;letter-spacing:.04em}.section-label p{margin:0;color:var(--muted);font-size:12px}.layout{display:grid;grid-template-columns:minmax(0,1fr);gap:18px;align-items:start}.panel{min-width:0;background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:18px 18px 14px;border-bottom:1px solid var(--line)}.panel-title{margin:0;font-size:17px;letter-spacing:-.02em}.panel-kicker{margin:4px 0 0;color:var(--muted);font-size:12px}.log-tools{display:flex;align-items:center;gap:8px}.search{width:min(220px,42vw);border:1px solid var(--line);border-radius:9px;padding:8px 10px;color:var(--ink);background:#fbfcfc}.table-scroll{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:11px 18px;text-align:left;border-bottom:1px solid #e8eeed;font-size:13px;white-space:nowrap}th{color:var(--muted);font-size:11px;font-weight:750;letter-spacing:.08em;text-transform:uppercase;background:#fbfcfc}tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:#f7fbfa}.domain{font-weight:680;color:var(--ink);white-space:normal;overflow-wrap:anywhere;max-width:360px}.client{color:var(--muted);font-variant-numeric:tabular-nums}.reason{display:inline-flex;padding:3px 7px;border-radius:999px;background:var(--teal-soft);color:var(--teal-dark);font-size:11px;font-weight:700}.reason.custom{background:#fff1da;color:#89500d}.reason.client{background:#fae6e3;color:#993c35}.age{color:var(--muted);font-variant-numeric:tabular-nums}.empty{padding:30px 18px;color:var(--muted);text-align:center}.log-foot{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 18px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.pager{display:flex;gap:6px}.pager button{padding:5px 9px}.pager button:disabled{opacity:.45;cursor:not-allowed}.log-error{display:none;margin:0 18px 14px;padding:9px 11px;border-radius:8px;color:var(--red);background:#fff2f0;font-size:12px}.log-error.show{display:block}
.side{min-width:0;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px}.side .panel-head{padding-bottom:13px}.client-table th,.client-table td{padding-left:16px;padding-right:16px}.client-table td:nth-child(3),.client-table td:nth-child(4){text-align:right}.num{font-variant-numeric:tabular-nums}.block-num{color:var(--red)}.allow-num{color:var(--teal)}.badge{display:inline-flex;padding:2px 6px;border-radius:999px;background:#fae6e3;color:var(--red);font-size:10px;font-weight:800;margin-left:5px}.custom-list{padding:0 16px}.custom-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 2px;border-bottom:1px solid #e8eeed}.custom-row:last-child{border-bottom:0}.domain-form,.settings-form,.upload-form{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.panel-body{padding:15px 16px}.field{min-width:0;flex:1;border:1px solid var(--line);border-radius:8px;background:#fbfcfc;color:var(--ink);padding:8px 10px}.field.short{flex:0 1 70px;min-width:58px}.hint{margin:8px 0 0;color:var(--muted);font-size:11px}.form-status{color:var(--muted);font-size:12px}.settings-grid{display:grid;gap:13px}.settings-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.settings-row label{width:100%;font-size:12px;font-weight:700;color:var(--muted)}.file{max-width:100%;font-size:12px}.stack{display:grid;gap:8px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.offline{color:var(--red)!important}.sr-only{position:absolute;left:0;top:0;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.list-status{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.list-status strong{font-size:13px}.list-status .form-status{margin-left:auto}.profile-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.4fr);gap:14px;align-items:start}.profile-picker{display:grid;gap:8px}.profile-picker label{font-size:12px;font-weight:700;color:var(--muted)}.profile-picker select{width:100%;border:1px solid var(--line);border-radius:8px;background:#fbfcfc;color:var(--ink);padding:9px 10px}.profile-meta{display:grid;gap:5px}.profile-meta p{margin:0;color:var(--muted);font-size:12px}.profile-meta strong{color:var(--ink)}.profile-progress{width:100%;height:8px;accent-color:var(--teal)}.allow-note{margin:0 0 12px;color:var(--muted);font-size:12px}.allow-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 2px;border-bottom:1px solid #e8eeed}.allow-row:last-child{border-bottom:0}.allow-list{padding:0 16px;max-height:280px;overflow:auto}.allow-list .empty{padding:18px 2px}.log-action{padding:5px 8px;font-size:11px}.profile-error{display:none;width:100%;margin:4px 0 0;padding:8px 10px;border-radius:8px;color:var(--red);background:#fff2f0;font-size:12px}.profile-error.show{display:block}
@media(max-width:860px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.layout{grid-template-columns:minmax(0,1fr)}.side{display:flex;flex-direction:column}.side .panel:last-child{grid-column:1/-1}}@media(max-width:560px){.wrap{width:min(100% - 22px,1160px);padding-top:18px}.topbar{display:block}.host{display:inline-flex;margin-top:14px}.status{align-items:flex-start;flex-wrap:wrap}.status-actions{width:100%;justify-content:flex-end}.status-actions select{flex:1}.panel-head{display:block}.log-tools{margin-top:12px}.search{width:100%}.metrics{gap:8px}.metric{padding:13px}.metric-value{font-size:20px}.side{display:flex}th,td{padding-left:12px;padding-right:12px}.log-foot{align-items:flex-start;flex-direction:column}.pager{align-self:flex-end}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
 </style></head><body><main class="wrap"><header class="topbar"><div><div class="eyebrow">Protección de tu red</div><h1 class="brand">AdBlock</h1><p class="sub">Consulta qué se bloquea y controla la protección de tu red.</p></div><div id="connection" class="host"><span class="dot" aria-hidden="true"></span><span id="host">Conectando…</span></div></header>
<section id="blockbar" class="status" aria-live="polite"><div id="blockdot" class="shield" aria-hidden="true">✓</div><div class="status-copy"><span id="blockstate" class="status-title">Comprobando bloqueo…</span><span id="blocknote" class="status-note">Sincronizando con el dispositivo</span></div><div class="status-actions"><label class="sr-only" for="pausedur">Duración de la pausa</label><select id="pausedur"><option value="30">30 segundos</option><option value="300" selected>5 minutos</option><option value="1800">30 minutos</option><option value="0">Hasta reactivar</option></select><button id="pausebtn" class="primary" type="button" disabled>Pausar</button></div></section>
<section id="sys" class="metrics" aria-label="Estado del sistema"></section>
<div class="section-label"><h2>ACTIVIDAD</h2><p id="lastRefresh">Actualizando…</p></div><div class="layout"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Consultas bloqueadas</h2><p class="panel-kicker">Las últimas solicitudes rechazadas por el dispositivo</p></div><div class="log-tools"><label class="sr-only" for="logSearch">Filtrar por dominio o cliente</label><input id="logSearch" class="search" maxlength="63" type="search" placeholder="Buscar dominio o IP…" autocomplete="off"></div></div><p id="logError" class="log-error" role="alert"></p><div class="table-scroll"><table aria-live="polite"><thead><tr><th>Dominio</th><th>Cliente</th><th>Tipo</th><th>Motivo</th><th>Hace</th><th><span class="sr-only">Acción</span></th></tr></thead><tbody id="logBody"></tbody></table></div><div class="log-foot"><span id="logMeta">Cargando historial…</span><div class="pager"><button id="prevPage" type="button" disabled>Anterior</button><button id="nextPage" type="button" disabled>Siguiente</button></div></div></section>
<aside class="side"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Clientes</h2><p class="panel-kicker">Actividad observada desde el último arranque</p></div></div><div class="table-scroll"><table class="client-table"><thead><tr><th>IP</th><th>MAC</th><th>Bloq.</th><th>Permit.</th><th><span class="sr-only">Acción</span></th></tr></thead><tbody id="clientBody"></tbody></table></div></section><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Dominios propios</h2><p class="panel-kicker">Reglas añadidas manualmente</p></div></div><div class="panel-body"><form id="domainForm" class="domain-form"><label class="sr-only" for="dom">Dominio que bloquear</label><input id="dom" class="field" maxlength="253" placeholder="ads.example.com" autocomplete="off"><button class="primary" type="submit">Bloquear</button></form></div><div id="customBody" class="custom-list"></div></section></aside></div>
<div class="section-label"><h2>LISTAS DE BLOQUEO</h2><p>El perfil activo se mantiene hasta que la nueva lista termine de aplicarse.</p></div><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Perfil de protección</h2><p class="panel-kicker">Elige el nivel de cobertura de HaGeZi y revisa el cambio antes de aplicarlo.</p></div><div class="list-status"><strong id="listsCount">— dominios</strong><span id="listsStatus" class="form-status" role="status">Cargando…</span></div></div><div class="panel-body profile-grid"><div class="profile-picker"><label for="profileSelect">Perfil seleccionado</label><select id="profileSelect" disabled><option value="custom">Personalizada · lista actual</option><option value="light">Ligero · HaGeZi Light</option><option value="balanced">Equilibrado · HaGeZi PRO (recomendado)</option><option value="strict">Estricto · HaGeZi PRO++ (puede romper sitios)</option></select><button id="profileApply" class="primary" type="button" disabled>Aplicar perfil</button><button id="listsCheck" type="button" disabled>Actualizar lista ahora</button><p id="listsError" class="profile-error" role="alert"></p></div><div class="profile-meta"><p id="listsActive">Activa: —</p><p id="listsSelected">Seleccionada: —</p><progress id="listsProgress" class="profile-progress" max="100" value="0" hidden></progress><p id="listsProgressText">La lista personalizada conserva la configuración existente.</p><p class="hint">Personalizada usa la carga binaria y la URL configuradas más abajo; elegir un perfil no cambia la lista hasta que termine la comprobación y aplicación.</p></div></div></section><section class="panel" style="margin-top:12px"><div class="panel-head"><div><h2 class="panel-title">Dominios permitidos</h2><p class="panel-kicker">Excepciones persistentes para esta red</p></div><span id="allowCount" class="form-status">0 / 200</span></div><div class="panel-body"><p class="allow-note">Permite este dominio y sus subdominios aunque aparezca en una blocklist o regla propia. Las prohibiciones de clientes siguen teniendo prioridad.</p><form id="allowlistForm" class="domain-form"><label class="sr-only" for="allowDomain">Dominio que permitir</label><input id="allowDomain" class="field" maxlength="253" placeholder="example.com" autocomplete="off"><button id="allowAdd" class="primary" type="submit" disabled>Permitir dominio</button><span id="allowStatus" class="form-status" role="status"></span></form></div><div id="allowBody" class="allow-list"></div></section>
<div class="section-label"><h2>CONFIGURACIÓN</h2><p>Los cambios se aplican al dispositivo al guardarlos.</p></div><section class="panel"><div class="panel-body settings-grid"><div><h2 class="panel-title">Personalizada · Blocklist local</h2><p class="panel-kicker">Carga una lista binaria ya compilada, sin USB.</p></div><form id="uploadForm" class="upload-form"><label class="sr-only" for="blf">Archivo blocklist.bin</label><input id="blf" class="file" type="file" accept=".bin"><button type="submit">Subir blocklist</button><span id="upmsg" class="form-status" role="status"></span></form><p class="hint">Genera <span class="mono">blocklist.bin</span> con <span class="mono">tools/build_blocklist.py</span>.</p></div></section>
<section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Personalizada · Actualización remota</h2><p class="panel-kicker">Descarga una blocklist precompilada según un horario.</p></div><form id="updateForm" class="settings-form"><label class="sr-only" for="uurl">URL de blocklist</label><input id="uurl" class="field" type="url" placeholder="https://host/blocklist.bin" autocomplete="off"><label class="sr-only" for="uiv">Intervalo en horas</label><input id="uiv" class="field short" type="number" min="1" max="720" value="24"><span aria-hidden="true">h</span><button type="submit">Guardar</button><button id="fetchNow" type="button">Descargar ahora</button><span id="ustat" class="form-status" role="status">—</span></form><p class="hint">El dispositivo mantiene la última respuesta aquí; una URL vacía desactiva la descarga personalizada. El intervalo también se usa para los perfiles HaGeZi.</p></div></section>
<section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Firmware · OTA</h2><p class="panel-kicker">El dispositivo valida el binario y reinicia en la nueva versión.</p></div><form id="firmwareForm" class="upload-form"><label class="sr-only" for="fwb">Archivo de firmware</label><input id="fwb" class="file" type="file" accept=".bin"><button type="submit">Flashear firmware</button><span id="fwmsg" class="form-status" role="status"></span></form><p class="hint">Selecciona <span class="mono">firmware.bin</span> o el binario de tu perfil.</p></div></section><section class="panel" style="margin-top:12px"><div class="panel-body settings-grid"><div><h2 class="panel-title">Actualización desde GitHub</h2><p class="panel-kicker">Busca una release pública para este perfil y verifica tamaño y SHA-256.</p></div><div class="upload-form"><button id="githubCheck" type="button" disabled>Comprobar actualizaciones</button><button id="githubInstall" class="primary" type="button" disabled>Instalar actualización</button><span id="githubStatus" class="form-status" role="status">Nunca comprobado</span></div><p id="fwIdentity" class="hint">Leyendo versión instalada…</p><p class="hint">Releases de felipedelpozo/adblock. La instalación conserva WiFi, listas y ajustes.</p></div></section><p class="hint" style="margin-top:18px"><strong>Últimas 64 consultas:</strong> historial reciente; se vacía al reiniciar la placa. Los contadores de esta sesión siguen la misma regla.</p></main>
<script>
const $=id=>document.getElementById(id);
const state={logPage:0,logQuery:'',logBusy:false,logPending:false,statsBusy:false,searchTimer:0,offline:false,updateDirty:false,githubNonce:'',githubVersion:'',githubPending:false,githubCanInstall:false,listsReady:false,listsBusy:false,listsFetchBusy:false,listsAction:false,listsProfileDirty:false,listsProfileDraft:'',listsAppliedProfile:'custom',listsNonce:'',listsPollTimer:0,allowed:[],allowlistBusy:false};
function fmt(value){return Number(value||0).toLocaleString('es-ES')}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node}
function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}
function setOffline(isOffline){state.offline=isOffline;const connection=$('connection');connection.classList.toggle('offline',isOffline);$('host').textContent=isOffline?'Dispositivo sin conexión':'@ '+(connection.dataset.ip||'dispositivo');connection.querySelector('.dot').classList.toggle('off',isOffline);if(isOffline){$('githubCheck').disabled=true;$('githubInstall').disabled=true}}
async function request(path,options){const response=await fetch(path,options);if(!response.ok){const error=new Error('HTTP '+(response.status||0));error.status=response.status||0;throw error}return response}
function actionStatus(node,message,error){node.textContent=message;node.classList.toggle('offline',!!error)}
function metric(label,value,tone){const card=el('div','metric');card.append(el('div','metric-value '+(tone||''),value),el('div','metric-label',label));return card}
function renderMetrics(s){const sys=$('sys');clear(sys);sys.append(metric('Bloqueadas',fmt(s.blocked),'warn'),metric('Permitidas',fmt(s.allowed),'good'),metric('Dominios en blocklist',fmt(s.domains)),metric('Clientes observados',s.clients.length),metric('WiFi',s.rssi+' dBm'),metric('Temperatura',s.temp+' °C'),metric('RAM libre',Math.round(s.heap/1024)+' KB'),metric('Uptime',s.uptime))}
function renderStatus(s){const on=s.blocking!==false;const bar=$('blockbar');bar.classList.toggle('paused',!on);$('blockdot').textContent=on?'✓':'Ⅱ';$('blockstate').textContent=on?'Bloqueo activo':'Bloqueo en pausa';$('blockstate').dataset.on=on?'1':'0';$('blocknote').textContent=on?'Las consultas coincidentes se rechazan ahora':(s.resumeIn>0?'Se reanuda en '+s.resumeIn+' s':'Pausa indefinida; reactiva cuando quieras');$('pausebtn').textContent=on?'Pausar':'Reanudar';$('pausebtn').classList.toggle('primary',on);$('pausebtn').disabled=false;$('pausedur').hidden=!on}
function renderClients(clients){const body=$('clientBody');clear(body);const rows=(clients||[]).slice().sort((a,b)=>(b.blocked+b.allowed)-(a.blocked+a.allowed));if(!rows.length){const row=el('tr');const cell=el('td','empty','Sin clientes todavía');cell.colSpan=5;row.append(cell);body.append(row);return}rows.forEach(client=>{const row=el('tr');const ip=el('td','client',client.ip);if(client.banned)ip.append(el('span','badge','BLOQUEADO'));row.append(ip,el('td','mono client',client.mac),el('td','num block-num',fmt(client.blocked)),el('td','num allow-num',fmt(client.allowed)));const action=el('button','quiet danger',client.banned?'Desbloquear':'Bloquear');action.type='button';action.dataset.ip=client.ip;const actionCell=el('td');actionCell.append(action);row.append(actionCell);body.append(row)})}
function renderCustom(domains){const body=$('customBody');clear(body);if(!domains||!domains.length){body.append(el('p','empty','Todavía no hay dominios propios.'));return}domains.forEach(domain=>{const row=el('div','custom-row');row.append(el('span','domain',domain));const button=el('button','quiet danger','Quitar');button.type='button';button.dataset.domain=domain;row.append(button);body.append(row)})}
const PROFILE_NAMES={custom:'Personalizada · lista actual',light:'Ligero · HaGeZi Light',balanced:'Equilibrado · HaGeZi PRO (recomendado)',strict:'Estricto · HaGeZi PRO++ (puede romper sitios)'};
function profileValue(value){return Object.prototype.hasOwnProperty.call(PROFILE_NAMES,value)?value:'custom'}
function profileLabel(value){return PROFILE_NAMES[profileValue(value)]}
function listsErrorMessage(error,fallback){const status=error&&error.status;if(status===400)return 'La solicitud no es válida. Revisa el perfil o el dominio.';if(status===403)return 'La sesión del dashboard ya no es válida. Recarga la página.';if(status===409)return 'La lista ya se está actualizando. Espera a que termine.';return fallback}
function allowlistErrorMessage(error,remove){const status=error&&error.status;if(status===400)return 'El dominio no es válido.';if(status===403)return 'La sesión del dashboard ya no es válida. Recarga la página.';if(status===404||status===409)return remove?'Ese dominio ya no está en permitidos.':'No se pudo permitir: ya está permitido o la lista ha alcanzado el máximo de 200 dominios.';return 'No se pudo cambiar la lista de permitidos.'}
function showListsError(message){const node=$('listsError');node.textContent=message||'';node.classList.toggle('show',!!message)}
function listsHeaders(){return {'X-CSRF-Token':state.listsNonce}}
async function listsRequest(path,options){const opts=options||{};const headers=Object.assign({},opts.headers||{},listsHeaders());return request(path,Object.assign({},opts,{headers}))}
function renderAllowed(domains){const body=$('allowBody');clear(body);const rows=(Array.isArray(domains)?domains:[]).slice(0,200);state.allowed=rows.slice();$('allowCount').textContent=rows.length+' / 200';if(!rows.length){body.append(el('p','empty','Todavía no hay excepciones guardadas.'));return}rows.forEach(domain=>{const row=el('div','allow-row');row.append(el('span','domain',domain));const button=el('button','quiet danger','Quitar');button.type='button';button.dataset.allowDomain=domain;button.disabled=state.allowlistBusy||state.listsBusy||state.listsAction||!state.listsReady;row.append(button);body.append(row)})}
function updateListsControls(){const disabled=!state.listsReady||state.listsBusy||state.listsAction;$('profileSelect').disabled=disabled;$('profileApply').disabled=disabled||state.listsProfileDraft===state.listsAppliedProfile||state.listsProfileDraft==='custom';$('listsCheck').disabled=disabled||state.listsProfileDraft==='custom';$('allowAdd').disabled=!state.listsReady||state.listsBusy||state.allowlistBusy}
function renderLists(data){const selected=profileValue(data.selectedProfile);const applied=profileValue(data.appliedProfile);const busy=!!data.busy;const progress=Math.max(0,Math.min(100,Number(data.progress)||0));const select=$('profileSelect');state.listsAppliedProfile=applied;if(!state.listsProfileDirty||selected===state.listsProfileDraft&&!busy){state.listsProfileDraft=selected;state.listsProfileDirty=false;select.value=selected}const domains=Math.max(0,Number(data.domains)||0);$('listsCount').textContent=fmt(domains)+' dominios';$('listsActive').textContent='Activa: '+profileLabel(applied);$('listsSelected').textContent='Seleccionada: '+profileLabel(state.listsProfileDraft||selected);$('listsStatus').textContent=data.status|| (busy?'Actualizando…':'Lista preparada');$('listsProgress').value=progress;$('listsProgress').hidden=!busy&&progress<=0;$('listsProgressText').textContent=busy?'Progreso: '+progress+'% · el perfil activo sigue siendo '+profileLabel(applied):progress>=100?'Lista aplicada: '+profileLabel(applied):'La lista personalizada conserva la configuración existente.';if(Array.isArray(data.allowed))renderAllowed(data.allowed);state.listsBusy=busy;updateListsControls()}
async function loadLists(){if(state.listsFetchBusy||state.listsAction)return;state.listsFetchBusy=true;try{const data=await(await request('/lists.json')).json();if(!data||typeof data!=='object')throw new Error('Invalid lists response');state.listsNonce=typeof data.nonce==='string'?data.nonce:state.listsNonce;state.listsReady=true;renderLists(data);showListsError('')}catch(error){showListsError(listsErrorMessage(error,'No se pudo cargar el estado de las listas. Reintentando…'))}finally{state.listsFetchBusy=false}}
function scheduleListsPoll(){clearTimeout(state.listsPollTimer);state.listsPollTimer=setTimeout(()=>{loadLists()},450)}
async function listsAction(path,successMessage){if(!state.listsReady||state.listsAction||state.listsBusy)return;state.listsAction=true;showListsError('');updateListsControls();let accepted=false;try{const response=await listsRequest(path,{method:'POST'});if(response.status!==202)throw Object.assign(new Error('Unexpected response'),{status:response.status});accepted=true;state.listsBusy=true;$('listsStatus').textContent=successMessage;$('listsProgress').value=0;$('listsProgress').hidden=false;$('listsProgressText').textContent='Solicitud aceptada; esperando aplicación. El perfil activo no ha cambiado.';updateListsControls();scheduleListsPoll()}catch(error){showListsError(listsErrorMessage(error,'No se pudo iniciar la actualización de la lista.'));}finally{state.listsAction=false;if(!accepted)state.listsBusy=false;updateListsControls()}}
function applyProfile(){const value=profileValue($('profileSelect').value);if(value==='custom')return;state.listsProfileDraft=value;listsAction('/lists/profile?p='+encodeURIComponent(value),'Solicitud aceptada; esperando aplicación…')}
function checkLists(){if(state.listsProfileDraft==='custom')return;listsAction('/lists/check','Comprobación aceptada; esperando resultado…')}
async function changeAllowlist(domain,remove){if(!state.listsReady||state.allowlistBusy||state.listsBusy||state.listsAction)return;const value=String(domain||'').trim().toLowerCase().replace(/^\.+|\.+$/g,'');if(!value||value.length>253){$('allowStatus').textContent='Escribe un dominio válido';$('allowStatus').classList.add('offline');return}state.allowlistBusy=true;$('allowStatus').classList.remove('offline');$('allowStatus').textContent=remove?'Quitando…':'Guardando…';try{const response=await listsRequest((remove?'/allowlist/remove?d=':'/allowlist/add?d=')+encodeURIComponent(value),{method:'POST'});if(response.status!==200)throw Object.assign(new Error('Unexpected response'),{status:response.status});$('allowStatus').textContent=remove?'Excepción quitada':'Dominio permitido';if(!remove)$('allowDomain').value='';await loadLists()}catch(error){$('allowStatus').textContent=allowlistErrorMessage(error,remove);$('allowStatus').classList.add('offline')}finally{state.allowlistBusy=false;renderAllowed(state.allowed);updateListsControls()}}
function age(seconds){const s=Math.max(0,Number(seconds)||0);if(s<60)return 'hace '+Math.round(s)+' s';if(s<3600)return 'hace '+Math.floor(s/60)+' min';if(s<86400)return 'hace '+Math.floor(s/3600)+' h';return 'hace '+Math.floor(s/86400)+' d'}
function queryType(type){const n=Number(type);return n===1?'A':n===28?'AAAA':'TYPE '+(Number.isFinite(n)?n:'?')}
function reasonLabel(reason){return reason==='client'?'cliente':reason==='custom'?'propio':'blocklist'}
function renderLog(data){const body=$('logBody');clear(body);const entries=data.entries||[];if(!entries.length){const row=el('tr');const cell=el('td','empty',state.logQuery?'No hay coincidencias para este filtro.':'No hay consultas bloqueadas todavía.');cell.colSpan=6;row.append(cell);body.append(row)}else entries.forEach(entry=>{const row=el('tr');row.append(el('td','domain',entry.domain),el('td','client',entry.client),el('td','mono client',queryType(entry.type)));const kind=entry.reason==='custom'?'custom':entry.reason==='client'?'client':'';const reason=el('span','reason '+kind,reasonLabel(entry.reason));const reasonCell=el('td');reasonCell.append(reason);const actionCell=el('td');const allow=el('button','quiet log-action','Permitir');allow.type='button';allow.dataset.allowDomain=String(entry.domain||'');const clientBanned=entry.reason==='client';allow.disabled=clientBanned||!state.listsReady||state.allowlistBusy||state.listsBusy;if(clientBanned)allow.title='Desbloquea el cliente en Clientes';actionCell.append(allow);row.append(reasonCell,el('td','age',age(entry.ageSeconds)),actionCell);body.append(row)});const start=entries.length?data.offset+1:0;const end=data.offset+entries.length;$('logMeta').textContent=data.count+(data.count===1?' coincidencia · mostrando ':' coincidencias · mostrando ')+start+'–'+end+' de '+data.total+' retenidas';$('prevPage').disabled=data.offset<=0;$('nextPage').disabled=!data.more}
function requestLog(){if(state.logBusy){state.logPending=true;return}loadLog()}
async function loadLog(){if(state.logBusy){state.logPending=true;return}state.logBusy=true;state.logPending=false;const page=state.logPage;const query=state.logQuery;const error=$('logError');error.classList.remove('show');const path='/blocked.json?offset='+(page*16)+'&limit=16&q='+encodeURIComponent(query.slice(0,63));try{const data=await(await request(path)).json();if(page!==state.logPage||query!==state.logQuery){state.logPending=true;return}const maxPage=Math.max(0,Math.ceil((Number(data.count)||0)/16)-1);if(state.logPage>maxPage){state.logPage=maxPage;state.logPending=true;return}renderLog(data);$('lastRefresh').textContent='Actualizado '+new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});setOffline(false)}catch(_){error.textContent='No se pudo cargar el historial. Reintentando…';error.classList.add('show');$('prevPage').disabled=true;$('nextPage').disabled=true;setOffline(true)}finally{state.logBusy=false;if(state.logPending){state.logPending=false;requestLog()}}}
function renderFirmware(s){state.githubNonce=s.githubNonce||'';state.githubVersion=s.githubVersion||'';state.githubCanInstall=!!s.githubCanInstall;$('fwIdentity').textContent='Instalado: '+(s.fwVersion||'—')+' · '+(s.fwProfile||'—');$('githubStatus').textContent=(s.githubStatus||'Nunca comprobado')+(s.githubBusy&&s.githubProgress>0?' · '+s.githubProgress+'%':'');$('githubCheck').disabled=!state.githubNonce||!!s.githubBusy||state.githubPending;$('githubInstall').disabled=!state.githubNonce||!state.githubCanInstall||!!s.githubBusy||state.githubPending;$('githubInstall').textContent=state.githubCanInstall?'Instalar '+state.githubVersion:'Instalar actualización'}
async function loadStats(){if(state.statsBusy)return;state.statsBusy=true;try{const s=await(await request('/stats.json')).json();const connection=$('connection');connection.dataset.ip=s.ip;renderStatus(s);renderMetrics(s);renderClients(s.clients);renderCustom(s.custom);if(!state.updateDirty){$('uurl').value=s.upurl||'';$('uiv').value=s.upiv||24}$('ustat').textContent=s.upstat||'—';renderFirmware(s);setOffline(false)}catch(_){setOffline(true);$('blockstate').textContent='Dispositivo sin conexión';$('blocknote').textContent='No se pudo actualizar el estado; revisando de nuevo…'}finally{state.statsBusy=false}}
async function togglePause(){const button=$('pausebtn');button.disabled=true;try{const path=$('blockstate').dataset.on==='1'?'/pause?s='+$('pausedur').value:'/resume';await request(path);await loadStats()}catch(_){actionStatus($('blocknote'),'No se pudo cambiar el estado',true)}finally{button.disabled=false}}
$('pausebtn').addEventListener('click',togglePause);$('logSearch').addEventListener('input',event=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>{state.logQuery=event.target.value.trim().slice(0,63);state.logPage=0;requestLog()},280)});$('prevPage').addEventListener('click',()=>{if(state.logPage){state.logPage--;requestLog()}});$('nextPage').addEventListener('click',()=>{if(!$('nextPage').disabled){state.logPage++;requestLog()}});
$('clientBody').addEventListener('click',async event=>{const button=event.target.closest('button[data-ip]');if(!button)return;button.disabled=true;try{await request('/ban?ip='+encodeURIComponent(button.dataset.ip));await loadStats()}catch(_){actionStatus($('blocknote'),'No se pudo cambiar el cliente',true)}finally{button.disabled=false}});
$('customBody').addEventListener('click',async event=>{const button=event.target.closest('button[data-domain]');if(!button)return;button.disabled=true;try{await request('/unblock?d='+encodeURIComponent(button.dataset.domain));await loadStats()}catch(_){actionStatus($('blocknote'),'No se pudo quitar el dominio',true)}finally{button.disabled=false}});
$('domainForm').addEventListener('submit',async event=>{event.preventDefault();const input=$('dom'),domain=input.value.trim();if(!domain)return;const button=event.submitter||event.target.querySelector('button');button.disabled=true;try{await request('/addblock?d='+encodeURIComponent(domain));input.value='';await loadStats()}catch(_){actionStatus($('blocknote'),'No se pudo añadir el dominio',true)}finally{button.disabled=false}});
$('uurl').addEventListener('input',()=>{state.updateDirty=true});$('uiv').addEventListener('input',()=>{state.updateDirty=true});$('updateForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter||event.target.querySelector('button');button.disabled=true;try{const hours=Math.max(1,parseInt($('uiv').value,10)||24);await request('/setupdate?u='+encodeURIComponent($('uurl').value.trim())+'&h='+hours);state.updateDirty=false;actionStatus($('ustat'),'Guardado');await loadStats()}catch(_){actionStatus($('ustat'),'No se pudo guardar',true)}finally{button.disabled=false}});
$('fetchNow').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;actionStatus($('ustat'),'Descargando…');try{const text=await(await request('/fetchnow')).text();actionStatus($('ustat'),text);await loadStats()}catch(_){actionStatus($('ustat'),'Descarga fallida',true)}finally{button.disabled=false}});
function uploadOptions(url,data){const options={method:'POST',body:data};if(url==='/upload')options.headers={'X-CSRF-Token':state.listsNonce};return options}
async function upload(formId,inputId,statusId,url,success,failure){$(formId).addEventListener('submit',async event=>{event.preventDefault();const input=$(inputId),file=input.files[0],status=$(statusId),button=event.submitter||event.target.querySelector('button');if(!file){actionStatus(status,'Selecciona un archivo',true);return}button.disabled=true;actionStatus(status,'Subiendo '+(file.size/1048576).toFixed(2)+' MB…');const data=new FormData();data.append('f',file);try{const response=await request(url,uploadOptions(url,data));actionStatus(status,success(response.ok));input.value='';setTimeout(loadStats,600)}catch(_){actionStatus(status,failure,true)}finally{button.disabled=false}})}
upload('uploadForm','blf','upmsg','/upload',ok=>ok?'✓ Blocklist actualizada':'✗ Blocklist rechazada','✗ Falló la subida');upload('firmwareForm','fwb','fwmsg','/update',ok=>ok?'✓ Reiniciando; reconecta en unos 15 s':'✗ Firmware rechazado','✗ Falló la subida');
async function githubAction(install){if(state.githubPending||!state.githubNonce||(install&&!state.githubCanInstall))return;const version=state.githubVersion;if(install&&!confirm('¿Instalar '+version+' en este dispositivo? Reiniciará al verificar el firmware; conservará WiFi, listas y ajustes.'))return;state.githubPending=true;$('githubCheck').disabled=true;$('githubInstall').disabled=true;actionStatus($('githubStatus'),install?'Iniciando instalación…':'Comprobando releases…');try{await request(install?'/github/install?v='+encodeURIComponent(version):'/github/check',{method:'POST',headers:{'X-CSRF-Token':state.githubNonce}});actionStatus($('githubStatus'),install?'Descargando y verificando…':'Comprobación en curso…')}catch(_){actionStatus($('githubStatus'),'No se pudo iniciar la operación; vuelve a comprobar',true)}finally{state.githubPending=false;setTimeout(loadStats,500)}}
$('githubCheck').addEventListener('click',()=>githubAction(false));$('githubInstall').addEventListener('click',()=>githubAction(true));
$('profileSelect').addEventListener('change',event=>{if(!state.listsReady||state.listsBusy)return;state.listsProfileDraft=profileValue(event.target.value);state.listsProfileDirty=true;$('listsSelected').textContent='Seleccionada: '+profileLabel(state.listsProfileDraft);updateListsControls()});$('profileApply').addEventListener('click',applyProfile);$('listsCheck').addEventListener('click',checkLists);$('allowlistForm').addEventListener('submit',event=>{event.preventDefault();changeAllowlist($('allowDomain').value,false)});$('allowBody').addEventListener('click',event=>{const button=event.target.closest('button[data-allow-domain]');if(button)changeAllowlist(button.dataset.allowDomain,true)});$('logBody').addEventListener('click',event=>{const button=event.target.closest('button[data-allow-domain]');if(button)changeAllowlist(button.dataset.allowDomain,false)});
setTimeout(loadLists,0);loadStats();requestLog();setInterval(loadStats,4000);setInterval(()=>{if(document.activeElement!==$('logSearch'))requestLog()},4000);setInterval(()=>{if(!state.listsAction&&!state.listsFetchBusy)loadLists()},4000);
</script></body></html>)HTML";
